/**
 * settings 分区文案（自 en 主表拆出：主表超单文件行数上限；键集与主表 HEAD 严格一致 + 本增补新键）。
 */
export const enSettings = {
    title: 'Settings',
    navGroupBasics: 'Basics',
    navGroupAgent: 'Capabilities',
    navGroupData: 'Data',
    backToWorkspace: 'Back to workspace',
    navOnboarding: 'Getting started',
    followSystem: 'System',
    providersTitle: 'Channels',
    providersDesc: 'Model service channels and the default model.',
    searchProviders: 'Search channels…',
    searchNoResults: 'No matches.',
    providersEmpty: 'No channels configured yet. Add one to start chatting.',
    addProvider: 'Add channel',
    providersCount: (count: number): string => `${count} channels`,
    apiFormatOptions: {
      'anthropic-messages': 'Anthropic Messages',
      'openai-completions': 'OpenAI Completions',
    },
    apiFormatUnknown: (value: string): string => `Custom · ${value}`,
    providerFormTitleNew: 'New channel',
    providerFormTitleEdit: 'Edit channel',
    providerFormSubtitleNew: 'Set the endpoint, API format and models. The channel becomes selectable once saved.',
    providerFormSubtitleEdit: 'Update this channel. Saving restarts the host so the model catalog reloads.',
    providerFieldName: 'Name',
    providerFieldNameHint: 'Cannot change after creation (the name keys models.json)',
    providerFieldBaseUrl: 'Base URL',
    providerFieldBaseUrlHint: 'Endpoint root, e.g. https://open.bigmodel.cn/api/paas/v4',
    providerFieldApi: 'API format',
    providerFieldApiHint: 'Pick the protocol your endpoint speaks.',
    providerFieldKey: 'API key',
    providerFieldKeyHint: 'Stored locally (encrypted); never echoed back.',
    providerKeyKeepHint: 'Leave blank to keep the saved key',
    providerKeyClear: 'Clear key',
    providerKeyClearConfirm: 'Confirm clear',
    providerKeyClearFailed: 'Could not clear the key. Try again.',
    providerModelsLabel: 'Models',
    providerModelsHint: 'Model ids must match the server; reasoning/vision only affect what the composer offers.',
    providerModelsEmpty: 'No models yet. Add one below.',
    providerModelAdd: 'Add',
    providerModelRemove: 'Remove model',
    providerSaved: 'Saved',
    providerMeta: (apiLabel: string, count: number): string => `${apiLabel} · ${count} models`,
    providerRemoveHint: (name: string): string => `Remove channel "${name}"? Its API key is removed too.`,
    providerRemoveFailed: 'Could not remove the channel. Try again.',
    providerBackToList: 'Channels',
    modelThinkingOn: 'Reasoning declared (click to disable)',
    modelThinkingOff: 'Declare reasoning support (click to enable)',
    modelVisionOn: 'Vision declared (click to disable)',
    modelVisionOff: 'Declare vision support (click to enable; required for multimodal models or images are dropped)',
    keyPresent: 'key saved',
    keyMissing: 'key missing',
    save: 'Save',
    remove: 'Remove',
    confirmRemove: 'Confirm remove',
    formIncomplete: 'Name, base URL and at least one model id are required.',
    formFailed: 'Save failed. Check the values and try again.',
    runtimeTitle: 'Runtime',
    runtimeDesc: 'System monitoring, worker management and diagnostics. Polls live while this section is open.',
    runtimeAttention: 'Attention: host not ready or a worker faulted',
    historyTitle: 'History',
    historyArchivedTitle: 'Archived',
    historyRestore: 'Restore',
    historyDesc: 'Saved sessions to resume or manage.',
    historyEmpty: 'No saved sessions yet.',
    historyFilterAll: 'All projects',
    historyFilter: (project: string): string => project,
    pin: 'Pin',
    unpin: 'Unpin',
    revealInFinder: 'Reveal in file manager',
    historyMsgs: 'msgs',
    refresh: 'Refresh',
    preferenceSaveFailed: 'Saving the preference failed. Try again.',
    permissionSaveFailed: 'Saving permission settings failed. Try again.',
    permissionsTitle: 'Permissions',
    permissionsDesc: 'Defaults applied to new conversations (permission mode and thinking level).',
    permissionsDefaultMode: 'Default permission mode',
    permissionsDefaultModeHint: 'Used when a conversation does not pick a mode; changing it does not affect live conversations.',
    permissionsDefaultThinking: 'Default thinking level',
    permissionsDefaultThinkingHint: 'Off / Low / Medium / High for new conversations; per-session levels take priority.',
    permissionsUnset: 'Hub default',
    permModeOptions: {
      plan: 'Plan',
      default: 'Default',
      acceptEdits: 'Accept edits',
      fullAuto: 'Full auto',
    },
    permissionsLoading: 'Loading permission settings…',
    generalTitle: 'General',
    generalDesc: 'Language, appearance and basic behavior.',
    generalLanguage: 'Language',
    generalLanguageHint: 'Display language of the interface.',
    appearanceLabel: 'Appearance',
    appearanceLight: 'Light',
    appearanceDark: 'Dark',
    appearanceHint: 'Color scheme of the interface; applies immediately.',
    generalTrustedDefault: 'Trust new projects by default',
    generalTrustedHint: 'Trusted sessions load project extensions and project-level agents from the working directory.',
    generalIdleRecycle: 'Idle worker recycle',
    generalIdleRecycleHint: 'Workers idle beyond this window are archived; the conversation reopens on demand.',
    onboardingCardTitle: 'Guided setup',
    onboardingCardDesc: 'Re-run the setup guide to configure providers, pick a default model and create your first conversation.',
    onboardingCardAction: 'Re-run',
    generalSaveFailed: 'Save failed. Try again.',
    generalDefaultModelInvalid: 'Default model is no longer available; new conversations fall back to the first model.',
    defaultModelInvalidShort: 'Not available',
    agentsTitle: 'Agents',
    agentsDesc: 'Agent definitions available to conversations.',
    agentsEmpty: 'No agent definitions found.',
    agentsUserBadge: 'User',
    agentsProjectBadge: 'Project · trusted only',
    agentsTools: (count: number): string => (count === 1 ? '1 tool' : `${count} tools`),
    agentsNew: 'New subagent',
    agentsSearch: 'Search subagents…',
    agentsFormTitleNew: 'New subagent',
    agentsFormTitleEdit: 'Edit subagent',
    agentsFormSubtitleNew: 'Set the name, tools and system prompt; returns to the list on save.',
    agentsFormSubtitleEdit: 'Adjust the subagent configuration; returns to the list on save.',
    agentsGroupUser: 'User',
    agentsGroupProject: 'Project',
    agentsCount: (count: number): string => (count === 1 ? '1 agent' : `${count} agents`),
    agentsEditAction: 'Edit',
    agentsRemoveAction: 'Delete',
    agentsConfirmRemove: 'Confirm delete',
    agentsRemoveHint: (name: string): string => `Deletes the definition ${name}.md; running subagents are not affected.`,
    agentsFieldName: 'Name',
    agentsFieldNameHint: 'kebab-case invoke name and file name stem (lowercase letters, digits, hyphens).',
    agentsFieldDescription: 'Description',
    agentsFieldDescriptionHint: 'Tells the main conversation when to call this agent.',
    agentsFieldPrompt: 'System prompt',
    agentsFieldPromptHint: 'Responsibilities, tool usage and reply format of this agent.',
    agentsFieldModel: 'Model',
    agentsModelInherit: 'Inherit parent',
    agentsModelInheritHint: 'Uses the conversation model that starts the task.',
    agentsFieldTools: 'Tools',
    agentsToolsDefault: 'All tools',
    agentsToolsModeAll: 'All tools',
    agentsToolsModeCustom: 'Custom tools',
    agentsToolsAllHint: 'Uses all built-in tools.',
    agentsToolsPickEmpty: 'Custom tools require at least one selection.',
    agentsFieldScope: 'Scope',
    agentsScopeUser: 'User',
    agentsScopeUserHint: 'Global; available in every project.',
    agentsScopeProject: 'Project',
    agentsScopeProjectHint: 'Written to the project .my-agent/agents; trusted sessions only.',
    agentsScopeProjectNone: 'Pick a project',
    agentsSave: 'Save',
    agentsCancel: 'Cancel',
    agentsFormIncomplete: 'Name and description are required.',
    agentsNameInvalid: 'Name must be kebab-case: lowercase letters, digits and hyphens, starting with a letter or digit (fork and main are reserved).',
    agentsNameExists: 'An agent with this name already exists.',
    agentsSaveFailed: 'Save failed. Try again.',
    agentsRemoveFailed: 'Delete failed. Try again.',
    skillsTitle: 'Skills',
    skillsDesc: 'Enable or disable user-level skills.',
    searchSkills: 'Search skills…',
    skillsEmpty: 'No user-level skills installed.',
    skillsHint: 'User-level skills come from the agent skill directories. Disabled skills are unavailable in conversations (active conversations reopen automatically to apply; any running generation is interrupted). Project-level skills appear only in trusted sessions.',
    skillsRefresh: 'Refresh',
    skillSourceOptions: {
      builtin: 'Built-in',
      user: 'User',
      project: 'Project',
    },
    skillDisabledHint: 'Disabled: unavailable in conversations',
    skillToggleLabel: (name: string): string => `Toggle skill ${name}`,
    skillToggleFailed: 'Could not save the skill switch. Try again.',
    skillReopenFailed: 'A conversation failed to reopen; the skill switch is not applied to it yet.',
    defaultModelTitle: 'Default model',
    defaultModelNone: 'Not set (first available model)',
    cancelEdit: 'Cancel',
    testConnection: 'Test connection',
    testing: 'Testing…',
    testOk: (latencyMs: number): string => `OK · ${latencyMs} ms`,
    testFailed: (reason: string): string => `Failed (${reason})`,
    providerModelEdit: 'Edit model',
    providerModelTest: 'Test model',
    modelDialogAddTitle: 'Add model',
    modelDialogEditTitle: 'Edit model',
    modelDialogFieldId: 'Model ID',
    modelDialogFieldIdPlaceholder: 'Model ID',
    modelDialogFieldContextWindow: 'Context window',
    modelDialogFieldContextWindowPlaceholder: '1000000',
    modelDialogFieldMaxTokens: 'Max output tokens',
    modelDialogFieldMaxTokensPlaceholder: '128000',
    modelDialogFieldInputTypes: 'Input types',
    modelDialogFieldOutputTypes: 'Output types',
    modelDialogInputText: 'Text',
    modelDialogInputImage: 'Image',
    modelDialogInputVideo: 'Video',
    modelDialogInputPdf: 'PDF',
    modelDialogInputLocked: 'Always on',
    modelDialogUnsupported: 'Not supported by the runtime yet',
    modelDialogCancel: 'Cancel',
    modelDialogSave: 'Save',
    modelDialogIdRequired: 'Model id is required',
    modelDialogIdDuplicate: 'This model id already exists in the channel',
    modelDialogNumberInvalid: 'Enter a positive integer (or leave blank for the default)',
};
