/**
 * settings 分区文案（自 en 主表拆出：主表超单文件行数上限；键集与主表 HEAD 严格一致 + 本增补新键）。
 */
export const enSettings = {
    title: 'Settings',
    navGroupBasics: 'Basics',
    navGroupAgent: 'Capabilities',
    navGroupData: 'Data',
    backToWorkspace: 'Back to workspace',
    navOnboarding: 'Getting started',
    followSystem: 'System',
    providersTitle: 'Channels',
    providersDesc: 'Model service channels and the default model.',
    searchProviders: 'Search channels…',
    searchNoResults: 'No matches.',
    providersEmpty: 'No channels configured yet. Add one to start chatting.',
    addProvider: 'Add channel',
    providersCount: (count: number): string => `${count} channels`,
    apiFormatOptions: {
      'openai-completions': 'OpenAI compatible · Chat Completions',
      'openai-responses': 'OpenAI · Responses',
      'anthropic-messages': 'Anthropic · Messages',
      'google-generative-ai': 'Google · Generative AI',
      'mistral-conversations': 'Mistral · Conversations',
    },
    apiFormatUnknown: (value: string): string => `Custom · ${value}`,
    providerFormTitleNew: 'New channel',
    providerFormTitleEdit: 'Edit channel',
    providerFormSubtitleNew: 'Set the endpoint, API format and models. The channel becomes selectable once saved.',
    providerFormSubtitleEdit: 'Update this channel. Saving restarts the host so the model catalog reloads.',
    providerFieldName: 'Name',
    providerFieldNameHint: 'Cannot change after creation (the name keys models.json)',
    providerFieldBaseUrl: 'Base URL',
    providerFieldBaseUrlHint: 'Endpoint root, e.g. https://open.bigmodel.cn/api/paas/v4',
    providerFieldApi: 'API format',
    providerFieldApiHint: 'Pick the protocol your endpoint speaks; only OpenAI-compatible formats support a thinking parameter format.',
    providerFieldKey: 'API key',
    providerFieldKeyHint: 'Stored locally (encrypted); never echoed back.',
    providerKeyKeepHint: 'Leave blank to keep the saved key',
    providerKeyClear: 'Clear key',
    providerKeyClearConfirm: 'Confirm clear',
    providerKeyClearFailed: 'Could not clear the key. Try again.',
    providerModelsLabel: 'Models',
    providerModelsHint: 'Model ids must match the server; reasoning/vision only affect what the composer offers.',
    providerModelsEmpty: 'No models yet. Add one below.',
    providerModelAdd: 'Add',
    providerModelRemove: 'Remove model',
    providerSaved: 'Saved',
    providerMeta: (apiLabel: string, count: number): string => `${apiLabel} · ${count} models`,
    providerRemoveHint: (name: string): string => `Remove channel "${name}"? Its API key is removed too.`,
    providerRemoveFailed: 'Could not remove the channel. Try again.',
    providerBackToList: 'Channels',
    modelThinkingOn: 'Reasoning declared (click to disable)',
    modelThinkingOff: 'Declare reasoning support (click to enable)',
    modelVisionOn: 'Vision declared (click to disable)',
    modelVisionOff: 'Declare vision support (click to enable; required for multimodal models or images are dropped)',
    thinkingFormatLabel: 'Thinking parameter format',
    thinkingFormatHint: 'Match the parameter your endpoint accepts; thinking levels become selectable once a model declares reasoning.',
    thinkingFormatOptions: {
      default: 'Default · reasoning_effort',
      zai: 'Zhipu GLM · thinking toggle',
      qwen: 'Qwen · enable_thinking',
      deepseek: 'DeepSeek · thinking toggle',
      openrouter: 'OpenRouter · reasoning',
      together: 'Together · reasoning',
      'string-thinking': 'thinking string',
      'ant-ling': 'Ant Ling · reasoning',
    },
    keyPresent: 'key saved',
    keyMissing: 'key missing',
    save: 'Save',
    remove: 'Remove',
    confirmRemove: 'Confirm remove',
    formIncomplete: 'Name, base URL and at least one model id are required.',
    formFailed: 'Save failed. Check the values and try again.',
    historyTitle: 'History',
    historyArchivedTitle: 'Archived',
    historyRestore: 'Restore',
    historyDesc: 'Saved sessions to resume or manage.',
    historyEmpty: 'No saved sessions yet.',
    historyFilterAll: 'All projects',
    historyFilter: (project: string): string => project,
    pin: 'Pin',
    unpin: 'Unpin',
    revealInFinder: 'Reveal in file manager',
    historyMsgs: 'msgs',
    refresh: 'Refresh',
    preferenceSaveFailed: 'Saving the preference failed. Try again.',
    permissionSaveFailed: 'Saving permission rules failed. Try again.',
    permissionsTitle: 'Permissions',
    permissionsDesc: 'Approval rules for tool execution.',
    permissionsMode: 'Mode',
    permissionsModeAsk: 'Ask every time',
    permissionsModeAllowAll: 'Allow all',
    permissionsModeBlockAll: 'Block all',
    permissionsModeHint: 'Decision order: mode first, then blocked patterns, then allowed patterns, otherwise ask.',
    permissionsGlobHint: "Patterns: * matches any characters (including /); everything else is literal.",
    permissionsBash: 'Bash commands',
    permissionsWrite: 'File writes',
    permissionsEdit: 'File edits',
    permissionsAllow: 'Always allow',
    permissionsBlock: 'Always block',
    permissionsAddPattern: 'Add pattern…',
    permissionsSave: 'Save rules',
    permissionsSaveFailed: 'Save failed. Try again.',
    permissionsSaved: 'Rules saved.',
    permissionsLoading: 'Loading permission rules…',
    permissionsScopeGlobal: 'All conversations',
    permissionsScopeSession: 'This conversation',
    permissionsFollowGlobal: 'This conversation follows the global rules.',
    permissionsCreateSession: 'Create separate rules',
    permissionsFollowGlobalAction: 'Follow global rules',
    diagnosticsTitle: 'Diagnostics',
    diagnosticsDesc: 'Host status and troubleshooting.',
    diagnosticsPhase: 'Host phase',
    diagnosticsRegistry: 'Registry sessions',
    diagnosticsStderr: 'Host stderr (tail)',
    diagnosticsRestart: 'Restart host',
    diagnosticsEmpty: 'Diagnostics not loaded yet.',
    generalTitle: 'General',
    generalDesc: 'Language, appearance and basic behavior.',
    generalLanguage: 'Language',
    generalLanguageHint: 'Display language of the interface.',
    appearanceLabel: 'Appearance',
    appearanceLight: 'Light',
    appearanceDark: 'Dark',
    appearanceHint: 'Color scheme of the interface; applies immediately.',
    generalTrustedDefault: 'Trust new projects by default',
    generalTrustedHint: 'Trusted sessions load project extensions and project-level agents from the working directory.',
    onboardingCardTitle: 'Guided setup',
    onboardingCardDesc: 'Re-run the setup guide to configure providers, pick a default model and create your first conversation.',
    onboardingCardAction: 'Re-run',
    generalSaveFailed: 'Save failed. Try again.',
    generalDefaultModelInvalid: 'Default model is no longer available; new conversations fall back to the first model.',
    defaultModelInvalidShort: 'Not available',
    agentsTitle: 'Agents',
    agentsDesc: 'Agent definitions available to conversations.',
    agentsEmpty: 'No agent definitions found.',
    agentsUserBadge: 'User',
    agentsProjectBadge: 'Project · trusted only',
    agentsTools: (count: number): string => (count === 1 ? '1 tool' : `${count} tools`),
    agentsNew: 'New subagent',
    agentsSearch: 'Search subagents…',
    agentsFormTitleNew: 'New subagent',
    agentsFormTitleEdit: 'Edit subagent',
    agentsFormSubtitleNew: 'Set the name, tools and system prompt; returns to the list on save.',
    agentsFormSubtitleEdit: 'Adjust the subagent configuration; returns to the list on save.',
    agentsGroupUser: 'User',
    agentsGroupProject: 'Project',
    agentsCount: (count: number): string => (count === 1 ? '1 agent' : `${count} agents`),
    agentsEditAction: 'Edit',
    agentsRemoveAction: 'Delete',
    agentsConfirmRemove: 'Confirm delete',
    agentsRemoveHint: (name: string): string => `Deletes the definition file ${name}.md; running subagents are not affected.`,
    agentsFieldName: 'Name',
    agentsFieldNameHint: 'Invoke name and file name; spaces and non-ASCII allowed, no / \\ : * ? " < > |',
    agentsFieldDescription: 'Description',
    agentsFieldDescriptionHint: 'Tells the main conversation when to call this agent.',
    agentsFieldPrompt: 'System prompt',
    agentsFieldPromptHint: 'Responsibilities, tool usage and reply format of this agent.',
    agentsFieldModel: 'Model',
    agentsModelInherit: 'Inherit parent',
    agentsModelInheritHint: 'Uses the conversation model that starts the task.',
    agentsFieldTools: 'Tools',
    agentsToolsDefault: 'All tools',
    agentsToolsModeAll: 'All tools',
    agentsToolsModeCustom: 'Custom tools',
    agentsToolsAllHint: 'Uses all built-in tools.',
    agentsToolsPickEmpty: 'Custom tools require at least one selection.',
    agentsFieldScope: 'Scope',
    agentsScopeUser: 'User',
    agentsScopeUserHint: 'Global; available in every project.',
    agentsScopeProject: 'Project',
    agentsScopeProjectHint: 'Written to the project .pi/agents; trusted sessions only.',
    agentsScopeProjectNone: 'Pick a project',
    agentsSave: 'Save',
    agentsCancel: 'Cancel',
    agentsFormIncomplete: 'Name and description are required.',
    agentsNameInvalid: 'Name must not contain / \\ : * ? " < > | or control characters, and must not start/end with a dot or whitespace.',
    agentsNameExists: 'An agent with this name already exists.',
    agentsSaveFailed: 'Save failed. Try again.',
    agentsRemoveFailed: 'Delete failed. Try again.',
    skillsTitle: 'Skills',
    skillsDesc: 'Enable or disable user-level skills.',
    searchSkills: 'Search skills…',
    skillsEmpty: 'No user-level skills installed.',
    skillsHint: 'User-level skills come from your agent skill directories. Disabled skills are unavailable in conversations (active conversations reopen automatically to apply; any running generation is interrupted). Project-level skills appear only in trusted sessions.',
    skillsRefresh: 'Refresh',
    skillDisabledHint: 'Disabled: unavailable in conversations',
    skillToggleLabel: (name: string): string => `Toggle skill ${name}`,
    skillToggleFailed: 'Could not save the skill switch. Try again.',
    skillReopenFailed: 'A conversation failed to reopen; the skill switch is not applied to it yet.',
    defaultModelTitle: 'Default model',
    defaultModelNone: 'Not set (first available model)',
    cancelEdit: 'Cancel',
    testConnection: 'Test connection',
    testing: 'Testing…',
    testOk: (latencyMs: number): string => `OK · ${latencyMs} ms`,
    testFailed: (reason: string): string => `Failed (${reason})`,
    providerModelEdit: 'Edit model',
    providerModelTest: 'Test model',
    modelDialogAddTitle: 'Add model',
    modelDialogEditTitle: 'Edit model',
    modelDialogFieldId: 'Model ID',
    modelDialogFieldIdPlaceholder: 'Model ID',
    modelDialogFieldContextWindow: 'Context window',
    modelDialogFieldContextWindowPlaceholder: '1000000',
    modelDialogFieldMaxTokens: 'Max output tokens',
    modelDialogFieldMaxTokensPlaceholder: '128000',
    modelDialogFieldInputTypes: 'Input types',
    modelDialogFieldOutputTypes: 'Output types',
    modelDialogInputText: 'Text',
    modelDialogInputImage: 'Image',
    modelDialogInputVideo: 'Video',
    modelDialogInputPdf: 'PDF',
    modelDialogInputLocked: 'Always on',
    modelDialogUnsupported: 'Not supported by the runtime yet',
    modelDialogCancel: 'Cancel',
    modelDialogSave: 'Save',
    modelDialogIdRequired: 'Model id is required',
    modelDialogIdDuplicate: 'This model id already exists in the channel',
    modelDialogNumberInvalid: 'Enter a positive integer (or leave blank for the default)',
};
