/** 英文文案表（key 结构 = 唯一真相；zh 表按同形状翻译）。 */
import { enFlow } from './en-flow';
import { enPulse } from './en-pulse';
import { enSettings } from './en-settings';
import {
  enErrorCopy,
  openEditorMissingCopy,
} from './en-error-copy';
export const en = {
  /** 标题行双色文案：名称重字重、产品线后缀轻字重（与设计稿一致） */
  appTitle: { name: 'Pai', suffix: 'Code' },
  sidebar: {
    search: 'Search',
    newTask: 'New task',
    hotkeyNewTask: (modifier: string): string => `${modifier}N`,
    hotkeySearch: (modifier: string): string => `${modifier}K`,
    viewGrouped: 'Grouped',
    viewProjects: 'Projects',
    pinnedSection: 'Pinned',
    pinSession: 'Pin',
    unpinSession: 'Unpin',
    showMore: 'Show more',
    working: 'Working',
    collapseSidebarHint: 'Collapse sidebar',
    expandSidebarHint: 'Show sidebar',
    settings: 'Settings',
    usage: 'Usage',
    automation: 'Automation',
    runtimeAttention: 'Host or worker needs attention',
    retireSession: 'Recycle worker',
    refresh: 'Refresh sessions',
    closeSession: 'Close conversation',
    renameSession: 'Rename conversation',
    renameFailed: 'Rename failed. Try again.',
    clearSearch: 'Clear search',
    collapseGroup: 'Toggle project group',
    noMatches: 'No matching conversations',
    emptyTasks: (hotkey: string): string => `No tasks yet — press ${hotkey} to start`,
    removeProject: 'Remove project',
    viewProjectFiles: 'View project files',
    projectFilesEmpty: 'No files to show',
    projectFilesLoading: 'Loading project files…',
    closeProjectFiles: 'Close',
    projectFilesCount: (count: number): string => `${count} ${count === 1 ? 'file' : 'files'}`,
    age: {
      justNow: 'now',
      minutes: (value: number): string => `${value}m`,
      hours: (value: number): string => `${value}h`,
      days: (value: number): string => `${value}d`,
    },
  },
  thread: {
    toggleMaximize: 'Toggle maximize',
    openDiff: 'Open Diff',
    turnFailedLabel: 'Request failed',
    turnAbortedLabel: 'Aborted',
    openMenu: ['Open in Finder', 'Open in Terminal', 'Open in Editor'] as [string, string, string],
    copyPath: 'Copy path',
    projectMenuAria: 'Project actions',
    toggleSplitView: 'Toggle split view',
    sessionMenuAria: 'Session actions',
    sessionRename: 'Rename',
    sessionCopyId: 'Copy session ID',
    sessionClose: 'Close session',
    sessionArchive: 'Archive session',
    renameTitleAria: 'Rename conversation',
    statusAria: 'Conversation status',
    status: {
      idle: 'Idle',
      running: 'Running',
      permission: 'Waiting for permission',
      compacting: 'Compacting',
      queued: 'Queued',
    },
    openFailed: (reason: string): string => `Failed to open (${reason}).`,
    openEditorMissing: openEditorMissingCopy,
    copyFailed: 'Copy failed. Try again.',
    emptyTitle: 'No messages yet',
    retryHydration: 'Retry',
    emptyHint: 'Describe a change, a question, or a task to get started.',
    /** 无会话空舞台（工作区无任何会话）：输入卡的全部会话域动作都无定址目标 */
    noSessionTitle: 'No sessions yet',
    noSessionHint: 'Start a new task (⌘N) to begin.',
    reloadTrusted: 'Reload as trusted',
    reloadUntrusted: 'Reload as untrusted',
    reloadTrustFailed: 'Reloading the conversation failed. Try again.',
  },
  palette: {
    aria: 'Command palette',
    placeholder: 'Search actions, sessions, files, commands…',
    empty: 'No matches',
    groups: {
      actions: 'Actions',
      sessions: 'Sessions',
      files: 'Files',
      commands: 'Commands',
      settings: 'Settings',
    },
    actions: {
      newTask: 'New task',
      openDiff: 'Open Diff panel',
      openAgents: 'Open agents panel',
      openFinder: 'Open in Finder',
      openTerminal: 'Open in Terminal',
      openEditor: 'Open in editor',
      copyPath: 'Copy project path',
      copySessionId: 'Copy session ID',
      closeSession: 'Close current session',
      openSettings: 'Open settings',
      openUsage: 'Open usage',
    },
  },
  panel: {
    tabDiff: 'Diff',
    tabAgents: 'Agents',
    close: 'Close panel',
    closeTab: (label: string): string => `Close ${label}`,
    file: {
      loading: 'Loading…',
      refresh: 'Refresh',
      preview: 'Preview',
      source: 'Source',
      modeAria: 'Switch display mode',
      truncated: 'File exceeds 2 MiB; showing the first 2 MiB.',
      errors: {
        notFound: 'File not found or deleted.',
        binary: 'Binary files cannot be previewed.',
        invalidParams: 'This path cannot be opened.',
        pathForbidden: 'This path is outside the current project.',
        cwdForbidden: 'The current directory is not accessible.',
        cwdNotFound: 'The current directory does not exist.',
        readFailed: 'Read failed. Try again.',
      },
    },
  },
  pulse: enPulse,
  flow: enFlow,
  composer: {
    placeholder: 'Ask anything, @tag files/folders, or / for commands and skills',
    queuePlaceholder: 'Type to queue a follow-up…',
    /** 排队消息卡片动作位 */
    queuedSendNow: 'Now',
    queuedEdit: 'Edit this queued message',
    queuedRemove: 'Remove this queued message',
    attach: 'Attach images and files',
    send: 'Send message',
    stop: 'Stop generating',
    sending: 'Sending',
    usageSummary: 'Usage',
    steerPlaceholder: 'Steer this agent…',
    steerFailed: (reason: string): string => `Steering failed (${reason}).`,
    noModels: 'No models yet — open Settings',
    hostDownModels: 'Host not connected — models unavailable',
    effortDefault: 'Default',
    slashAria: 'Command suggestions',
    fileAria: 'File suggestions',
    groupCommands: 'Commands',
    groupSkills: 'Skills',
    groupFiles: 'Files',
    slashHint: 'Type to search commands or skills',
    scrollDown: 'Scroll down',
    permissionMode: 'Permission mode',
    imageUnsupported: 'Only common image formats up to 20 MB can be attached (auto-compressed before sending).',
    removeImage: 'Remove image',
    projectSegment: 'Working directory',
    branchSegment: 'Current branch',
    branchLoading: 'Reading branches…',
    branchUnavailable: 'Branches unavailable',
    notARepo: 'Not a git repository',
    detachedHead: 'Detached HEAD',
  },
  dialogs: {
    confirmTitle: 'Confirmation required',
    /** 统一工具提示文案：工具 + 目标（文件路径/命令）一行。 */
    toolPrompt: (tool: string, target: string): string => `${tool} ${target}`,
    allow: 'Allow',
    deny: 'Deny',
    cancel: 'Cancel',
    morePending: (count: number): string => (count === 1 ? '1 more request waiting' : `${count} more requests waiting`),
    fromSubagent: (agent: string): string => `Requested by subagent · ${agent}`,
  },
  settings: enSettings,
  newTask: {
    greetingNight: 'Working late',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    subtitleNight: 'What are you still working on?',
    subtitleMorning: 'What do you want to build today?',
    subtitleAfternoon: 'What should we move forward?',
    subtitleEvening: 'What do you want to build tonight?',
    placeholder: 'Ask pai anything, use @ to add context, / for commands and skills',
    quickTasks: ['Understand this project', 'Fix the build failure', 'Add unit tests', 'Review recent changes'],
    quickTaskPrompt: (label: string): string => `Help me ${label.toLowerCase()}`,
    workspacePickerTitle: 'Choose a workspace',
    workspaceSearch: 'Search folders',
    workspaceEmpty: 'No matching folders',
    openFolder: 'Open folder…',
    trustedLabel: 'Trust this project',
    trustedHint: 'Trusted sessions load project extensions and project-level agents. Only enable it for repositories you own and review.',
    pickFailed: 'Could not open the directory picker. Try again.',
  },
  branch: {
    /** 分支面板（两页共用）：可访问名 + 列表分组标题。 */
    panelTitle: 'Branches',
    search: 'Search branches',
    empty: 'No matching branches',
    loading: 'Loading branches…',
    unavailable: 'Could not load branches. Try again.',
    dirtyFiles: (count: number): string => `Uncommitted changes: ${count} ${count === 1 ? 'file' : 'files'}`,
    lockReason: (count: number): string => `${count} ${count === 1 ? 'session is' : 'sessions are'} running — switching would rewrite their working baseline`,
    lockHintCreate: 'You can still create a new branch from the current HEAD (safe, no worktree change), or stop the session first.',
    conflictTitle: 'Switch blocked by uncommitted changes',
    conflictFilesTitle: (count: number): string => `Uncommitted changes to ${count} ${count === 1 ? 'file' : 'files'} would be overwritten:`,
    conflictHint: 'Commit or stash these files first (the agent in the session can do it for you).',
    createBranch: 'Create and checkout new branch…',
    openGraph: 'Git graph',
    createTitle: 'Create and checkout new branch',
    createSubtitle: 'Create a new local branch from the current HEAD and switch to it as soon as it is created.',
    createFieldLabel: 'Branch name',
    createFieldPlaceholder: 'e.g. feature/git-branch-switcher',
    createHelper: 'Only creating from the current HEAD is supported.',
    createSubmit: 'Create and switch',
  },
  gitGraph: {
    title: 'Git graph',
    colGraph: 'Graph',
    colDescription: 'Description',
    colDate: 'Date',
    colAuthor: 'Author',
    colCommit: 'Commit',
    refresh: 'Refresh',
    close: 'Close',
    loading: 'Loading commits…',
    unavailable: 'Could not load the git graph. Try again.',
    empty: 'This repository has no commits yet.',
    truncated: (count: number): string => `Showing the most recent ${count} commits`,
    headLabel: 'HEAD',
  },
  notices: {
    dismiss: 'Dismiss',
  },
  usage: {
    title: 'Usage',
    close: 'Close',
    contextTitle: 'Context',
    contextUsed: (pct: string): string => `${pct} used`,
    freeSpaceLabel: 'Free space',
    windowLabel: 'Context window',
    cacheHitLabel: 'Cache hit rate',
    cacheReadLabel: 'Total cache read',
    cacheWriteLabel: 'Total cache write',
    totalTokens: 'Total tokens',
    totalCost: 'Total cost',
    sessionsCount: (count: number): string => (count === 1 ? '1 conversation' : `${count} conversations`),
    byProject: 'By project',
    topSessions: 'Top conversations',
    empty: 'No live conversations with usage yet.',
    liveOnlyHint: 'Shows live conversations in this run. Usage history across restarts is not tracked yet.',
  },
  runtime: {
    title: 'Runtime',
    close: 'Close',
    healthLabel: 'Host health',
    healthHealthy: 'Healthy',
    healthDegraded: 'Attention',
    healthFailed: 'Fault',
    autoRefresh: 'auto refresh',
    hostPhase: 'Host phase',
    phaseStarting: 'Starting',
    phaseReady: 'Ready',
    phaseRestarting: 'Restarting',
    phaseFailed: 'Failed',
    heartbeat: 'Heartbeat',
    heartbeatAgo: (seconds: number): string => `${seconds}s ago`,
    heartbeatNever: 'no heartbeat yet',
    uptime: 'Uptime',
    restarts: 'Restarts',
    versions: 'Versions',
    bunLabel: 'Bun',
    pidLabel: 'PID',
    neverRestarted: 'never',
    capacity: 'Workers',
    stateLive: 'live',
    executing: 'executing',
    idle: 'idle',
    parked: 'parked',
    dead: 'dead',
    limit: 'limit',
    memory: 'Memory',
    systemMemory: 'System',
    appMemory: 'App',
    hubMemory: 'Hub',
    workersMemory: 'Workers',
    cpu: 'CPU',
    resourceTrend: 'Resource trend',
    workersTitle: 'Workers',
    filterAll: 'All',
    filterExecuting: 'Running',
    filterIdle: 'Idle',
    filterParked: 'Parked',
    filterDead: 'Faulted',
    columnSession: 'Conversation',
    /** 会话副行：项目名 + git 分支（分支在场才拼接） */
    sessionSubline: (project: string, branch: string | null): string => (branch === null ? project : `${project} @ ${branch}`),
    columnState: 'State',
    columnIdle: 'Idle',
    columnModel: 'Model',
    columnQueue: 'Queue',
    columnTokens: 'Tokens',
    columnMemory: 'Memory',
    columnActions: 'Actions',
    rowMenu: 'More actions',
    recyclePolicy: 'Auto recycle',
    recycleAllIdle: 'Recycle all idle',
    minutesOption: (minutes: number): string => `${minutes} min`,
    idleFor: (minutes: number): string => `idle ${minutes}m`,
    recycleIn: (seconds: number): string => `recycles in ${seconds}s`,
    manual: 'manual',
    actionStop: 'Stop',
    actionRecycle: 'Recycle',
    actionForceRecycle: 'Force recycle',
    actionOpen: 'Open',
    keepaliveOn: 'Keep alive',
    keepaliveOff: 'Clear keep-alive',
    rssRetireLimit: 'RSS retire limit',
    rssRetireOff: 'off',
    timeline: 'Events',
    timelineEmpty: 'No events recorded yet.',
    stderr: 'Host stderr (tail)',
    stderrLoad: 'Load stderr',
    stderrEmpty: 'No stderr output captured.',
    copySummary: 'Copy summary',
    summaryCopyFailed: 'Copy failed',
    summaryTitle: 'Pai runtime summary',
    summaryThreads: (live: number, parked: number, dead: number): string => `${live} live · ${parked} parked · ${dead} dead`,
    summaryCopied: 'Summary copied',
    exportBundle: 'Export diagnostics',
    exported: 'Diagnostics exported and revealed',
    restartHost: 'Restart host',
    hostUnavailable: 'Host unavailable — start of troubleshooting',
    noWorkers: 'No conversations yet',
    emptyHistory: 'Collecting resource samples…',
    fetchFailed: 'Runtime snapshot unavailable — is the app process up to date? Retry by switching sections.',
    recycleFailed: 'Recycle failed',
    keepaliveFailed: 'Keep-alive toggle failed',
    recycleSettingFailed: 'Failed to apply recycle setting',
    exportFailed: 'Export failed',
  },
  onboarding: {
    title: 'Welcome to pai',
    hint: 'Connect a provider and pick a model to start chatting. You can skip this and configure later in Settings.',
    stepProvider: 'Connect a provider',
    stepModel: 'Choose the default model',
    stepCwd: 'Pick a working directory',
    cwdField: '/path/to/your/project',
    next: 'Next',
    back: 'Back',
    finish: 'Start chatting',
    skip: 'Skip setup',
    noModelsYet: 'No models yet. Finish provider setup or refresh.',
    refreshModels: 'Refresh',
  },
  bootstrap: {
    loadingTitle: 'Starting up…',
    loadingHint: 'Connecting to the coding agent host.',
    failedTitle: 'Cannot start',
    bridgeHint: 'The preload bridge is unavailable. Relaunch the app from the desktop entry.',
    hostFailed: 'The agent host failed to start. Check Settings for provider configuration and the host-hub path.',
  },
  host: {
    downBanner: 'The agent host is not connected — models and sessions are unavailable (configured providers are unaffected).',
    downAction: 'Open Settings',
  },
  /** markdown 渲染器（streamdown）自带控件：代码块/表格/图示/图片的操作标签 */
  markdown: {
    copyCode: 'Copy code',
    downloadDiagram: 'Download diagram',
    downloadDiagramSvg: 'Download diagram as SVG',
    downloadDiagramPng: 'Download diagram as PNG',
    downloadDiagramMmd: 'Download diagram as MMD',
    viewFullscreen: 'View fullscreen',
    exitFullscreen: 'Exit fullscreen',
    mermaidFormatSvg: 'SVG',
    mermaidFormatPng: 'PNG',
    mermaidFormatMmd: 'MMD',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    resetView: 'Reset zoom and pan',
    copyTable: 'Copy table',
    copyTableAsMarkdown: 'Copy table as Markdown',
    copyTableAsCsv: 'Copy table as CSV',
    copyTableAsTsv: 'Copy table as TSV',
    downloadTable: 'Download table',
    downloadTableCsv: 'Download table as CSV',
    downloadTableMarkdown: 'Download table as Markdown',
    tableFormatMarkdown: 'Markdown',
    tableFormatCsv: 'CSV',
    tableFormatTsv: 'TSV',
    imageNotAvailable: 'Image not available',
    downloadImage: 'Download image',
    openExternalLink: 'Open external link?',
    externalLinkWarning: 'You are about to visit an external website.',
    close: 'Close',
    copyLink: 'Copy link',
    copied: 'Copied',
    openLink: 'Open link',
  },
  modelPicker: {
    title: 'Choose a model',
    searchPlaceholder: 'Search models...',
    empty: 'No matching models',
  },
  errorCopy: enErrorCopy,
};
