/** 英文文案表（key 结构 = 唯一真相；zh 表按同形状翻译）。 */
import { enSettings } from './en-settings';
export const en = {
  /** 标题行双色文案：名称重字重、产品线后缀轻字重（与设计稿一致） */
  appTitle: { name: 'Pai', suffix: 'Code' },
  sidebar: {
    search: 'Search',
    newTask: 'New task',
    pluginMarket: 'Plugin market',
    hotkeyNewTask: (modifier: string): string => `${modifier}N`,
    hotkeySearch: (modifier: string): string => `${modifier}K`,
    viewGrouped: 'Grouped',
    viewProjects: 'Projects',
    pinnedSection: 'Pinned',
    pinSession: 'Pin',
    unpinSession: 'Unpin',
    showMore: 'Show more',
    working: 'Working',
    collapseSidebarHint: 'Collapse sidebar',
    expandSidebarHint: 'Show sidebar',
    settings: 'Settings',
    workflows: 'Workflows',
    usage: 'Usage',
    automation: 'Automation',
    runtimeAttention: 'Host or worker needs attention',
    retireSession: 'Recycle worker',
    refresh: 'Refresh sessions',
    closeSession: 'Close conversation',
    renameSession: 'Rename conversation',
    renameFailed: 'Rename failed. Try again.',
    clearSearch: 'Clear search',
    collapseGroup: 'Toggle project group',
    noMatches: 'No matching conversations',
    emptyTasks: (hotkey: string): string => `No tasks yet — press ${hotkey} to start`,
    removeProject: 'Remove project',
    viewProjectFiles: 'View project files',
    projectFilesEmpty: 'No files to show',
    projectFilesLoading: 'Loading project files…',
    closeProjectFiles: 'Close',
    projectFilesCount: (count: number): string => `${count} ${count === 1 ? 'file' : 'files'}`,
    age: {
      justNow: 'now',
      minutes: (value: number): string => `${value}m`,
      hours: (value: number): string => `${value}h`,
      days: (value: number): string => `${value}d`,
    },
  },
  thread: {
    newTask: 'New',
    toggleMaximize: 'Toggle maximize',
    viewMenuAria: 'Open view',
    openDiff: 'Open Diff',
    turnFailedLabel: 'Request failed',
    turnAbortedLabel: 'Aborted',
    openMenu: ['Open in Finder', 'Open in Terminal', 'Open in Editor'] as [string, string, string],
    copyPath: 'Copy path',
    projectMenuAria: 'Project actions',
    toggleSplitView: 'Toggle split view',
    sessionMenuAria: 'Session actions',
    sessionRename: 'Rename',
    sessionCopyId: 'Copy session ID',
    sessionClose: 'Close session',
    sessionArchive: 'Archive session',
    renameTitleAria: 'Rename conversation',
    statusAria: 'Conversation status',
    status: {
      idle: 'Idle',
      running: 'Running',
      permission: 'Waiting for permission',
      compacting: 'Compacting',
      queued: 'Queued',
    },
    openFailed: (reason: string): string => `Failed to open (${reason}).`,
    openEditorMissing: 'No editor CLI found. Install the code or cursor CLI and retry.',
    copyFailed: 'Copy failed. Try again.',
    emptyTitle: 'No messages yet',
    retryHydration: 'Retry',
    emptyHint: 'Describe a change, a question, or a task to get started.',
    reloadTrusted: 'Reload as trusted',
    reloadUntrusted: 'Reload as untrusted',
    reloadTrustFailed: 'Reloading the conversation failed. Try again.',
  },
  palette: {
    aria: 'Command palette',
    placeholder: 'Search actions, sessions, files, commands…',
    empty: 'No matches',
    groups: {
      actions: 'Actions',
      sessions: 'Sessions',
      files: 'Files',
      commands: 'Commands',
      settings: 'Settings',
    },
    actions: {
      newTask: 'New task',
      openDiff: 'Open Diff panel',
      openAgents: 'Open agents panel',
      openFinder: 'Open in Finder',
      openTerminal: 'Open in Terminal',
      openEditor: 'Open in editor',
      copyPath: 'Copy project path',
      copySessionId: 'Copy session ID',
      closeSession: 'Close current session',
      openSettings: 'Open settings',
      openUsage: 'Open usage',
    },
  },
  panel: {
    tabDiff: 'Diff',
    tabAgents: 'Agents',
    close: 'Close panel',
    closeTab: (label: string): string => `Close ${label}`,
    file: {
      loading: 'Loading…',
      refresh: 'Refresh',
      preview: 'Preview',
      source: 'Source',
      modeAria: 'Switch display mode',
      truncated: 'File exceeds 2 MiB; showing the first 2 MiB.',
      openPickerTitle: 'Open file',
      openPickerSearch: 'Search project files',
      openPickerEmpty: 'No files to show',
      errors: {
        not_found: 'File not found or deleted.',
        binary_file: 'Binary files cannot be previewed.',
        invalid_path: 'This path cannot be opened.',
        path_forbidden: 'This path is outside the current project.',
        cwd_forbidden: 'The current directory is not accessible.',
        cwd_not_found: 'The current directory does not exist.',
        read_failed: 'Read failed. Try again.',
      },
    },
  },
  flow: {
    openDiff: 'Open Diff',
    steerPlaceholder: 'Steer this agent…',
    steerFailed: (reason: string): string => `Steering failed (${reason}).`,
    workingFor: 'Working for',
    workedFor: 'Worked for',
    /** Windows caption 三键（自绘标题栏） */
    captionMinimize: 'Minimize',
    captionMaximize: 'Maximize',
    captionRestore: 'Restore',
    captionClose: 'Close',
    /** 输入框徽标：工作子代理计数（按钮无障碍名） */
    agentsWorking: (count: number): string =>
      count === 1 ? '1 subagent working — open the Agents panel' : `${count} subagents working — open the Agents panel`,
    /** 折叠摘要：375 changed files */
    changedFiles: (count: number): string => (count === 1 ? '1 changed file' : `${count} changed files`),
    toggleAgents: 'Toggle agents panel',
    toggleDiff: 'Toggle diff panel',
    agentsPanelEmpty: 'No subagents spawned yet',
    diffPanelEmpty: 'No file changes in this session yet',
    statusWorking: 'Working',
    executing: 'Working…',
    toolStopped: 'Stopped',
    toolRunning: 'Running',
    /** 执行单元类型标签（未知工具直接显示工具名） */
    labelBash: 'Command',
    labelRead: 'Read',
    labelEdit: 'Edit',
    labelWrite: 'Write',
    labelSearch: 'Search',
    labelList: 'List',
    labelSubagent: 'Subagent',
    /** 思考单元收起态标签（运行中显 Thinking） */
    thought: 'Thought',
    /** 中断轮次的状态行：Stopped · 8m 0s */
    turnStoppedSummary: (elapsed: string): string => `Stopped · ${elapsed}`,
    /** 历史轮左缘锚点（无障碍名）：View the turn finished at 10:46 AM */
    turnAnchorAria: (time: string): string => `View the turn finished at ${time}`,
    /** 历史轮锚点带（无障碍名） */
    turnAnchorRailAria: 'Turn history navigation',
    thinking: 'Thinking',
    queued: (count: number): string => (count === 1 ? '1 queued message' : `${count} queued messages`),
    retrying: (attempt: number, maxAttempts: number): string => `Retrying (${attempt}/${maxAttempts})`,
    crashedBanner: 'This conversation\'s worker has exited. Sending a message resumes the session.',
    hydrateFailedTitle: 'Failed to load history',
    hydrateFailedHint: 'Could not read this conversation\'s history. You can retry.',
    compacting: 'Compacting context…',
    bashRunning: 'Running command…',
    editRerun: 'Edit & rerun (fork)',
    retryFromHere: 'Retry from here',
    forkFailed: 'Forking the conversation failed. Try again.',
    forkCancelled: 'The fork was cancelled by an extension; the conversation is unchanged.',
    forkedImageName: (index: number): string => `Image ${index}`,
    resumeFailed: 'Resuming the conversation failed. Try again.',
    stopConfirmTitle: 'Stop everything?',
    stopConfirmHint: 'This terminates all foreground and background subagents and cannot be undone.',
    stopConfirmYes: 'Stop all',
    stopConfirmNo: 'Cancel',
    bashNoImages: 'Direct commands cannot carry images. Remove them or send as a message.',
    bashFailed: (reason: string): string => `Command not run (${reason}).`,
    systemMessageLabel: 'System',
    sendFailed: (reason: string): string => `Message not sent (${reason}). Try again.`,
    toolFailed: (exitCode: number): string => `exit ${exitCode}`,
    copyMessage: 'Copy message',
    editMessage: 'Edit message',
    scrollToBottom: 'Scroll to latest',
    copyCommand: 'Copy command',
    copyOutput: 'Copy output',
    copied: 'Copied',
    outputLabel: 'Output',
    toggleOutput: 'Toggle command output',
    /** 面板汇总：2 working 3 settled */
    panelWorking: (count: number): string => (count === 1 ? '1 working' : `${count} working`),
    panelSettled: (count: number): string => (count === 1 ? '1 settled' : `${count} settled`),
    /** 面板右下角：Σ 6.6k tok */
    footerTokens: (tokens: string): string => `Σ ${tokens} tok`,
    /** 元信息段：51 tok / — tok */
    metaTokens: (tokens: string | null): string => (tokens === null ? '— tok' : `${tokens} tok`),
    /** 元信息段：7 tools；无工具调用时为 null，整段省略 */
    metaTools: (count: number): string | null => {
      if (count <= 0) return null;
      return count === 1 ? '1 tool' : `${count} tools`;
    },
  },
  composer: {
    placeholder: 'Ask anything, @tag files/folders, or / for commands and skills',
    queuePlaceholder: 'Type to queue a follow-up…',
    sendNow: 'Send now',
    editQueued: 'Edit queued message',
    removeQueued: 'Remove queued message',
    attach: 'Attach images and files',
    send: 'Send message',
    stop: 'Stop generating',
    contextUsage: 'Context used',
    steerPlaceholder: 'Steer this agent…',
    steerFailed: (reason: string): string => `Steering failed (${reason}).`,
    noModels: 'No models yet — open Settings',
    hostDownModels: 'Host not connected — models unavailable',
    effortUnavailable: 'Thinking unavailable',
    effortDefault: 'Default',
    slashAria: 'Command suggestions',
    fileAria: 'File suggestions',
    groupCommands: 'Commands',
    groupSkills: 'Skills',
    groupFiles: 'Files',
    slashHint: 'Type to search commands or skills',
    scrollDown: 'Scroll down',
    permissionMode: 'Permission mode',
    imageUnsupported: 'Only common image formats up to 20 MB can be attached (auto-compressed before sending).',
    removeImage: 'Remove image',
    projectSegment: 'Working directory',
    branchSegment: 'Current branch',
    branchLoading: 'Reading branches…',
    branchUnavailable: 'Branches unavailable',
    notARepo: 'Not a git repository',
    detachedHead: 'Detached HEAD',
    effortMenu: ['Low · 200K', 'Medium · 200K', 'High · 1M'],
  },
  dialogs: {
    confirmTitle: 'Confirmation required',
    selectTitle: 'Choose an option',
    inputTitle: 'Input requested',
    allow: 'Allow',
    deny: 'Deny',
    cancel: 'Cancel',
    send: 'Submit',
    noOptions: 'No options provided',
    morePending: (count: number): string => (count === 1 ? '1 more request waiting' : `${count} more requests waiting`),
    fromSubagent: (agent: string): string => `Requested by subagent · ${agent}`,
  },
  settings: enSettings,
  newTask: {
    greetingNight: 'Working late',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    subtitleNight: 'What are you still working on?',
    subtitleMorning: 'What do you want to build today?',
    subtitleAfternoon: 'What should we move forward?',
    subtitleEvening: 'What do you want to build tonight?',
    placeholder: 'Ask pai anything, use @ to add context, / for commands and skills',
    quickTasks: ['Understand this project', 'Fix the build failure', 'Add unit tests', 'Review recent changes'],
    quickTaskPrompt: (label: string): string => `Help me ${label.toLowerCase()}`,
    workspacePickerTitle: 'Choose a workspace',
    workspaceSearch: 'Search folders',
    workspaceEmpty: 'No matching folders',
    openFolder: 'Open folder…',
    trustedLabel: 'Trust this project',
    trustedHint: 'Trusted sessions load project extensions and project-level agents. Only enable it for repositories you own and review.',
    branchPickerTitle: 'Switch branch',
    branchSearch: 'Search branches',
    branchEmpty: 'No matching branches',
    createBranch: 'Create and checkout…',
    createBranchTitle: (from: string): string => `Create from ${from} and checkout`,
    createBranchField: 'New branch name',
    createBranchSubmit: 'Create and checkout',
    branchLoading: 'Loading branches…',
    branchUnavailable: 'Could not load branches. Try again.',
    branchFailed: (reason: string): string => {
      if (reason === 'branch_exists') return 'A branch with that name already exists. Pick another name.';
      if (reason === 'invalid_branch') return 'That branch name is not valid. Pick another name.';
      if (reason === 'dirty_worktree') return 'The working tree has uncommitted changes. Commit or stash them before switching branches.';
      if (reason === 'unknown_branch') return 'That branch no longer exists. Refresh and try again.';
      if (reason === 'not_a_repo') return 'That folder is not a git repository.';
      if (reason === 'git_unavailable') return 'git was not found on this system, so branches cannot be changed.';
      if (reason === 'cwd_not_found') return 'That working directory no longer exists.';
      return `Branch operation failed (${reason}).`;
    },
    pickFailed: 'Could not open the directory picker. Try again.',
    createFailed: (reason: string): string => {
      if (reason === 'host_unavailable') return 'The agent host is not ready (starting or restarting). Try again shortly.';
      if (reason.startsWith('Model not found')) return 'The selected model is unavailable. Check the provider configuration in Settings.';
      if (/cwd|directory|absolute|exist/i.test(reason)) return 'Could not start the conversation. Check the directory and try again.';
      return `Could not start the conversation (${reason}). Try again.`;
    },
  },
  notices: {
    dismiss: 'Dismiss',
  },
  usage: {
    title: 'Usage',
    close: 'Close',
    contextLabel: 'context',
    tokensLabel: 'tokens',
    costLabel: 'cost',
    messagesLabel: 'messages',
    toolCallsLabel: 'tool calls',
    totalTokens: 'Total tokens',
    totalCost: 'Total cost',
    sessionsCount: (count: number): string => (count === 1 ? '1 conversation' : `${count} conversations`),
    byProject: 'By project',
    topSessions: 'Top conversations',
    empty: 'No live conversations with usage yet.',
    liveOnlyHint: 'Shows live conversations in this run. Usage history across restarts is not tracked yet.',
  },
  runtime: {
    title: 'Runtime',
    close: 'Close',
    healthLabel: 'Host health',
    healthHealthy: 'Healthy',
    healthDegraded: 'Attention',
    healthFailed: 'Fault',
    autoRefresh: 'auto refresh',
    hostPhase: 'Host phase',
    phaseStarting: 'Starting',
    phaseReady: 'Ready',
    phaseRestarting: 'Restarting',
    phaseFailed: 'Failed',
    heartbeat: 'Heartbeat',
    heartbeatAgo: (seconds: number): string => `${seconds}s ago`,
    heartbeatNever: 'no heartbeat yet',
    uptime: 'Uptime',
    restarts: 'Restarts',
    versions: 'Versions',
    bunLabel: 'Bun',
    pidLabel: 'PID',
    neverRestarted: 'never',
    capacity: 'Workers',
    stateLive: 'live',
    executing: 'executing',
    idle: 'idle',
    parked: 'parked',
    dead: 'dead',
    subagentsInFlight: 'subagents in flight',
    limit: 'limit',
    memory: 'Memory',
    systemMemory: 'System',
    appMemory: 'App',
    hubMemory: 'Hub',
    workersMemory: 'Workers',
    cpu: 'CPU',
    resourceTrend: 'Resource trend',
    workersTitle: 'Workers',
    filterAll: 'All',
    filterExecuting: 'Running',
    filterIdle: 'Idle',
    filterParked: 'Parked',
    filterDead: 'Faulted',
    columnSession: 'Conversation',
    columnState: 'State',
    columnIdle: 'Idle',
    columnModel: 'Model',
    columnQueue: 'Queue',
    columnSubagents: 'Subagents',
    columnContext: 'Context',
    columnTokens: 'Tokens',
    columnMemory: 'Memory',
    columnActions: 'Actions',
    rowMenu: 'More actions',
    recyclePolicy: 'Auto recycle',
    recycleAllIdle: 'Recycle all idle',
    minutesOption: (minutes: number): string => `${minutes} min`,
    idleFor: (minutes: number): string => `idle ${minutes}m`,
    recycleIn: (seconds: number): string => `recycles in ${seconds}s`,
    manual: 'manual',
    actionStop: 'Stop',
    actionRecycle: 'Recycle',
    actionForceRecycle: 'Force recycle',
    actionOpen: 'Open',
    keepaliveOn: 'Keep alive',
    keepaliveOff: 'Clear keep-alive',
    timeline: 'Events',
    timelineEmpty: 'No events recorded yet.',
    stderr: 'Host stderr (tail)',
    stderrLoad: 'Load stderr',
    stderrEmpty: 'No stderr output captured.',
    copySummary: 'Copy summary',
    summaryCopyFailed: 'Copy failed',
    summaryTitle: 'Pai runtime summary',
    summaryThreads: (live: number, parked: number, dead: number): string => `${live} live · ${parked} parked · ${dead} dead`,
    summaryCopied: 'Summary copied',
    exportBundle: 'Export diagnostics',
    exported: 'Diagnostics exported and revealed',
    restartHost: 'Restart host',
    hostUnavailable: 'Host unavailable — start of troubleshooting',
    noWorkers: 'No conversations yet',
    emptyHistory: 'Collecting resource samples…',
    fetchFailed: 'Runtime snapshot unavailable — is the app process up to date? Retry by switching sections.',
    recycleFailed: 'Recycle failed',
    keepaliveFailed: 'Keep-alive toggle failed',
    recycleSettingFailed: 'Failed to apply recycle setting',
    exportFailed: 'Export failed',
  },
  onboarding: {
    title: 'Welcome to pai',
    hint: 'Connect a provider and pick a model to start chatting. You can skip this and configure later in Settings.',
    stepProvider: 'Connect a provider',
    stepModel: 'Choose the default model',
    stepCwd: 'Pick a working directory',
    cwdField: '/path/to/your/project',
    next: 'Next',
    back: 'Back',
    finish: 'Start chatting',
    skip: 'Skip setup',
    noModelsYet: 'No models yet. Finish provider setup or refresh.',
    refreshModels: 'Refresh',
  },
  bootstrap: {
    loadingTitle: 'Starting up…',
    loadingHint: 'Connecting to the coding agent host.',
    failedTitle: 'Cannot start',
    bridgeHint: 'The preload bridge is unavailable. Relaunch the app from the desktop entry.',
    hostFailed: 'The agent host failed to start. Check Settings for provider configuration and the pai-cli path.',
  },
  host: {
    downBanner: 'The agent host is not connected — models and sessions are unavailable (configured providers are unaffected).',
    downAction: 'Open Settings',
  },
  /** markdown 渲染器（streamdown）自带控件：代码块/表格/图示/图片的操作标签 */
  markdown: {
    copyCode: 'Copy code',
    downloadDiagram: 'Download diagram',
    downloadDiagramSvg: 'Download diagram as SVG',
    downloadDiagramPng: 'Download diagram as PNG',
    downloadDiagramMmd: 'Download diagram as MMD',
    viewFullscreen: 'View fullscreen',
    exitFullscreen: 'Exit fullscreen',
    mermaidFormatSvg: 'SVG',
    mermaidFormatPng: 'PNG',
    mermaidFormatMmd: 'MMD',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    resetView: 'Reset zoom and pan',
    copyTable: 'Copy table',
    copyTableAsMarkdown: 'Copy table as Markdown',
    copyTableAsCsv: 'Copy table as CSV',
    copyTableAsTsv: 'Copy table as TSV',
    downloadTable: 'Download table',
    downloadTableCsv: 'Download table as CSV',
    downloadTableMarkdown: 'Download table as Markdown',
    tableFormatMarkdown: 'Markdown',
    tableFormatCsv: 'CSV',
    tableFormatTsv: 'TSV',
    imageNotAvailable: 'Image not available',
    downloadImage: 'Download image',
    openExternalLink: 'Open external link?',
    externalLinkWarning: 'You are about to visit an external website.',
    close: 'Close',
    copyLink: 'Copy link',
    copied: 'Copied',
    openLink: 'Open link',
  },
  modelPicker: {
    title: 'Choose a model',
    searchPlaceholder: 'Search models...',
    empty: 'No matching models',
  },
};
