/** 英文文案表（key 结构 = 唯一真相；zh 表按同形状翻译）。 */
import { enSettings } from './en-settings';
export const en = {
  /** 标题行双色文案：名称重字重、产品线后缀轻字重（与设计稿一致） */
  appTitle: { name: 'T3', suffix: 'Code' },
  sidebar: {
    search: 'Search',
    newTask: 'New task',
    automation: 'Automation',
    pluginMarket: 'Plugin market',
    hotkeyNewTask: (modifier: string): string => `${modifier}N`,
    hotkeySearch: (modifier: string): string => `${modifier}K`,
    viewGrouped: 'Grouped',
    viewProjects: 'Projects',
    pinnedSection: 'Pinned',
    pinSession: 'Pin',
    unpinSession: 'Unpin',
    showMore: 'Show more',
    working: 'Working',
    collapseSidebarHint: 'Collapse sidebar',
    toggleSidebar: 'Toggle sidebar',
    settings: 'Settings',
    workflows: 'Workflows',
    usage: 'Usage',
    refresh: 'Refresh sessions',
    closeSession: 'Close conversation',
    renameSession: 'Rename conversation',
    renameFailed: 'Rename failed. Try again.',
    clearSearch: 'Clear search',
    collapseGroup: 'Toggle project group',
    noMatches: 'No matching conversations',
    emptyTasks: (hotkey: string): string => `No tasks yet — press ${hotkey} to start`,
    removeProject: 'Remove project',
    viewProjectFiles: 'View project files',
    projectFilesEmpty: 'No files to show',
    projectFilesLoading: 'Loading project files…',
    closeProjectFiles: 'Close',
    projectFilesCount: (count: number): string => `${count} ${count === 1 ? 'file' : 'files'}`,
    age: {
      justNow: 'now',
      minutes: (value: number): string => `${value}m`,
      hours: (value: number): string => `${value}h`,
      days: (value: number): string => `${value}d`,
    },
  },
  thread: {
    addAction: 'Add action',
    open: 'Open',
    commitPushPr: 'Commit, push & PR',
    toggleSplitView: 'Toggle split view',
    toggleMaximize: 'Toggle maximize',
    tabAdd: 'Add panel',
    openDiff: 'Open Diff',
    turnFailedLabel: 'Request failed',
    turnAbortedLabel: 'Aborted',
    openMenu: ['Open in Finder', 'Open in Terminal', 'Open in Editor'],
    commitMenu: ['Commit only', 'Create pull request', 'Push to remote'],
    emptyTitle: 'No messages yet',
    emptyHint: 'Describe a change, a question, or a task to get started.',
    reloadTrusted: 'Reload as trusted',
    reloadUntrusted: 'Reload as untrusted',
    reloadTrustFailed: 'Reloading the conversation failed. Try again.',
  },
  flow: {
    openDiff: 'Open Diff',
    closeDiffPanel: 'Close diff panel',
    steerPlaceholder: 'Steer this agent…',
    steerFailed: (reason: string): string => `Steering failed (${reason}).`,
    workingFor: 'Working for',
    workedFor: 'Worked for',
    /** Windows caption 三键（自绘标题栏） */
    captionMinimize: 'Minimize',
    captionMaximize: 'Maximize',
    captionRestore: 'Restore',
    captionClose: 'Close',
    /** 输入框徽标：工作子代理计数（按钮无障碍名） */
    agentsWorking: (count: number): string =>
      count === 1 ? '1 subagent working — open the Agents panel' : `${count} subagents working — open the Agents panel`,
    /** 折叠摘要：375 changed files */
    changedFiles: (count: number): string => (count === 1 ? '1 changed file' : `${count} changed files`),
    closeAgents: 'Close agents panel',
    toggleAgents: 'Toggle agents panel',
    toggleDiff: 'Toggle diff panel',
    panelTitle: 'DIRECT SPAWNS',
    agentsPanelEmpty: 'No subagents spawned yet',
    diffPanelTitle: 'FILE CHANGES',
    diffPanelEmpty: 'No file changes in this session yet',
    statusWorking: 'Working',
    executing: 'Working…',
    toolStopped: 'Stopped',
    toolRunning: 'Running',
    /** 执行单元类型标签（未知工具直接显示工具名） */
    labelBash: 'Command',
    labelRead: 'Read',
    labelEdit: 'Edit',
    labelWrite: 'Write',
    labelSearch: 'Search',
    labelList: 'List',
    labelSubagent: 'Subagent',
    /** 思考单元收起态标签（运行中显 Thinking） */
    thought: 'Thought',
    /** 中断轮次的状态行：Stopped · 8m 0s */
    turnStoppedSummary: (elapsed: string): string => `Stopped · ${elapsed}`,
    /** 历史轮左缘锚点（无障碍名）：View the turn finished at 10:46 AM */
    turnAnchorAria: (time: string): string => `View the turn finished at ${time}`,
    /** 历史轮锚点带（无障碍名） */
    turnAnchorRailAria: 'Turn history navigation',
    thinking: 'Thinking',
    queued: (count: number): string => (count === 1 ? '1 queued message' : `${count} queued messages`),
    retrying: (attempt: number, maxAttempts: number): string => `Retrying (${attempt}/${maxAttempts})`,
    crashedBanner: 'This conversation hit a worker crash and is recovering. The next command resumes it automatically.',
    compacting: 'Compacting context…',
    bashRunning: 'Running command…',
    editRerun: 'Edit & rerun (fork)',
    retryFromHere: 'Retry from here',
    forkFailed: 'Forking the conversation failed. Try again.',
    resumeFailed: 'Resuming the conversation failed. Try again.',
    stopConfirmTitle: 'Stop everything?',
    stopConfirmHint: 'This terminates all foreground and background subagents and cannot be undone.',
    stopConfirmYes: 'Stop all',
    stopConfirmNo: 'Cancel',
    bashNoImages: 'Direct commands cannot carry images. Remove them or send as a message.',
    bashFailed: (reason: string): string => `Command not run (${reason}).`,
    compactFailed: (reason: string): string => `Compaction failed (${reason}).`,
    systemMessageLabel: 'System',
    sendFailed: (reason: string): string => `Message not sent (${reason}). Try again.`,
    toolFailed: (exitCode: number): string => `exit ${exitCode}`,
    copyMessage: 'Copy message',
    editMessage: 'Edit message',
    scrollToBottom: 'Scroll to latest',
    copyCommand: 'Copy command',
    copyOutput: 'Copy output',
    copied: 'Copied',
    outputLabel: 'Output',
    toggleOutput: 'Toggle command output',
    /** 面板汇总：2 working 3 settled */
    panelWorking: (count: number): string => (count === 1 ? '1 working' : `${count} working`),
    panelSettled: (count: number): string => (count === 1 ? '1 settled' : `${count} settled`),
    /** 面板右下角：Σ 6.6k tok */
    footerTokens: (tokens: string): string => `Σ ${tokens} tok`,
    /** 元信息段：51 tok / — tok */
    metaTokens: (tokens: string | null): string => (tokens === null ? '— tok' : `${tokens} tok`),
    /** 元信息段：7 tools；无工具调用时为 null，整段省略 */
    metaTools: (count: number): string | null => {
      if (count <= 0) return null;
      return count === 1 ? '1 tool' : `${count} tools`;
    },
  },
  composer: {
    placeholder: 'Ask anything, @tag files/folders, $use skills, or / for commands',
    queuePlaceholder: 'Type to queue a follow-up…',
    sendNow: 'Send now',
    editQueued: 'Edit queued message',
    removeQueued: 'Remove queued message',
    attach: 'Attach images and files',
    send: 'Send message',
    stop: 'Stop generating',
    contextUsage: 'Context used',
    steerPlaceholder: 'Steer this agent…',
    steerFailed: (reason: string): string => `Steering failed (${reason}).`,
    compact: 'Compact context',
    noModels: 'No models yet — open Settings',
    hostDownModels: 'Host not connected — models unavailable',
    effortUnavailable: 'Thinking unavailable',
    slashAria: 'Command suggestions',
    fileAria: 'File suggestions',
    groupCommands: 'Commands',
    groupSkills: 'Skills',
    groupFiles: 'Files',
    slashHint: 'Type to search commands or skills',
    scrollDown: 'Scroll down',
    permissionMode: 'Permission mode',
    imageUnsupported: 'Only common image formats up to 20 MB can be attached (auto-compressed before sending).',
    removeImage: 'Remove image',
    projectSegment: 'Working directory',
    branchSegment: 'Current branch',
    branchLoading: 'Reading branches…',
    branchUnavailable: 'Branches unavailable',
    notARepo: 'Not a git repository',
    detachedHead: 'Detached HEAD',
    effortMenu: ['Low · 200K', 'Medium · 200K', 'High · 1M'],
  },
  dialogs: {
    confirmTitle: 'Confirmation required',
    selectTitle: 'Choose an option',
    inputTitle: 'Input requested',
    allow: 'Allow',
    deny: 'Deny',
    cancel: 'Cancel',
    send: 'Submit',
    noOptions: 'No options provided',
    morePending: (count: number): string => (count === 1 ? '1 more request waiting' : `${count} more requests waiting`),
    fromSubagent: (agent: string): string => `Requested by subagent · ${agent}`,
  },
  settings: enSettings,
  newTask: {
    greetingNight: 'Working late',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    subtitleNight: 'What are you still working on?',
    subtitleMorning: 'What do you want to build today?',
    subtitleAfternoon: 'What should we move forward?',
    subtitleEvening: 'What do you want to build tonight?',
    placeholder: 'Ask pai anything, use @ to add context',
    quickTasks: ['Understand this project', 'Fix the build failure', 'Add unit tests', 'Review recent changes'],
    quickTaskPrompt: (label: string): string => `Help me ${label.toLowerCase()}`,
    workspacePickerTitle: 'Choose a workspace',
    workspaceSearch: 'Search folders',
    workspaceEmpty: 'No matching folders',
    openFolder: 'Open folder…',
    trustedLabel: 'Trust this project',
    trustedHint: 'Trusted sessions load project extensions and project-level agents. Only enable it for repositories you own and review.',
    branchPickerTitle: 'Switch branch',
    branchSearch: 'Search branches',
    branchEmpty: 'No matching branches',
    createBranch: 'Create and checkout…',
    createBranchTitle: (from: string): string => `Create from ${from} and checkout`,
    createBranchField: 'New branch name',
    createBranchSubmit: 'Create and checkout',
    branchLoading: 'Loading branches…',
    branchUnavailable: 'Could not load branches. Try again.',
    branchFailed: (reason: string): string => {
      if (reason === 'branch_exists') return 'A branch with that name already exists. Pick another name.';
      if (reason === 'invalid_branch') return 'That branch name is not valid. Pick another name.';
      if (reason === 'dirty_worktree') return 'The working tree has uncommitted changes. Commit or stash them before switching branches.';
      if (reason === 'unknown_branch') return 'That branch no longer exists. Refresh and try again.';
      if (reason === 'not_a_repo') return 'That folder is not a git repository.';
      if (reason === 'git_unavailable') return 'git was not found on this system, so branches cannot be changed.';
      if (reason === 'cwd_not_found') return 'That working directory no longer exists.';
      return `Branch operation failed (${reason}).`;
    },
    pickFailed: 'Could not open the directory picker. Try again.',
    createFailed: (reason: string): string => {
      if (reason === 'host_unavailable') return 'The agent host is not ready (starting or restarting). Try again shortly.';
      if (reason.startsWith('Model not found')) return 'The selected model is unavailable. Check the provider configuration in Settings.';
      if (/cwd|directory|absolute|exist/i.test(reason)) return 'Could not start the conversation. Check the directory and try again.';
      return `Could not start the conversation (${reason}). Try again.`;
    },
  },
  notices: {
    dismiss: 'Dismiss',
  },
  usage: {
    title: 'Usage',
    close: 'Close',
    contextLabel: 'context',
    tokensLabel: 'tokens',
    costLabel: 'cost',
    messagesLabel: 'messages',
    toolCallsLabel: 'tool calls',
    totalTokens: 'Total tokens',
    totalCost: 'Total cost',
    sessionsCount: (count: number): string => (count === 1 ? '1 conversation' : `${count} conversations`),
    byProject: 'By project',
    topSessions: 'Top conversations',
    empty: 'No live conversations with usage yet.',
    liveOnlyHint: 'Shows live conversations in this run. Usage history across restarts is not tracked yet.',
  },
  onboarding: {
    title: 'Welcome to pai',
    hint: 'Connect a provider and pick a model to start chatting. You can skip this and configure later in Settings.',
    stepProvider: 'Connect a provider',
    stepModel: 'Choose the default model',
    stepCwd: 'Pick a working directory',
    cwdField: '/path/to/your/project',
    next: 'Next',
    back: 'Back',
    finish: 'Start chatting',
    skip: 'Skip setup',
    noModelsYet: 'No models yet. Finish provider setup or refresh.',
    refreshModels: 'Refresh',
  },
  bootstrap: {
    loadingTitle: 'Starting up…',
    loadingHint: 'Connecting to the coding agent host.',
    failedTitle: 'Cannot start',
    bridgeHint: 'The preload bridge is unavailable. Relaunch the app from the desktop entry.',
    hostFailed: 'The agent host failed to start. Check Settings for provider configuration and the pai-cli path.',
  },
  host: {
    downBanner: 'The agent host is not connected — models and sessions are unavailable (configured providers are unaffected).',
    downAction: 'Open Settings',
  },
  /** markdown 渲染器（streamdown）自带控件：代码块/表格/图示/图片的操作标签 */
  markdown: {
    copyCode: 'Copy code',
    downloadDiagram: 'Download diagram',
    downloadDiagramSvg: 'Download diagram as SVG',
    downloadDiagramPng: 'Download diagram as PNG',
    downloadDiagramMmd: 'Download diagram as MMD',
    viewFullscreen: 'View fullscreen',
    exitFullscreen: 'Exit fullscreen',
    mermaidFormatSvg: 'SVG',
    mermaidFormatPng: 'PNG',
    mermaidFormatMmd: 'MMD',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    resetView: 'Reset zoom and pan',
    copyTable: 'Copy table',
    copyTableAsMarkdown: 'Copy table as Markdown',
    copyTableAsCsv: 'Copy table as CSV',
    copyTableAsTsv: 'Copy table as TSV',
    downloadTable: 'Download table',
    downloadTableCsv: 'Download table as CSV',
    downloadTableMarkdown: 'Download table as Markdown',
    tableFormatMarkdown: 'Markdown',
    tableFormatCsv: 'CSV',
    tableFormatTsv: 'TSV',
    imageNotAvailable: 'Image not available',
    downloadImage: 'Download image',
    openExternalLink: 'Open external link?',
    externalLinkWarning: 'You are about to visit an external website.',
    close: 'Close',
    copyLink: 'Copy link',
    copied: 'Copied',
    openLink: 'Open link',
  },
  modelPicker: {
    title: 'Choose a model',
    searchPlaceholder: 'Search models...',
    empty: 'No matching models',
  },
};
