/**
 * settings 分区文案（自 zh 主表拆出：主表超单文件行数上限；键集与主表 HEAD 严格一致 + 本增补新键）。
 */
import type { enSettings } from './en-settings';

export const zhSettings: typeof enSettings = {
    title: '设置',
    navGroupBasics: '基础设置',
    navGroupAgent: 'Agent 能力',
    navGroupData: '数据与统计',
    backToWorkspace: '返回工作区',
    navOnboarding: '引导',
    followSystem: '跟随系统',
    providersTitle: '渠道',
    providersDesc: '模型服务渠道与默认模型。',
    searchProviders: '搜索渠道…',
    searchNoResults: '没有匹配结果。',
    providersEmpty: '还没有配置渠道，添加一个即可开始。',
    addProvider: '添加渠道',
    providersCount: (count: number): string => `${count} 个渠道`,
    apiFormatOptions: {
      'anthropic-messages': 'Anthropic Messages',
      'openai-completions': 'OpenAI Completions',
    },
    apiFormatUnknown: (value: string): string => `自定义 · ${value}`,
    providerFormTitleNew: '新建渠道',
    providerFormTitleEdit: '编辑渠道',
    providerFormSubtitleNew: '填写服务端地址、API 格式与模型清单，保存后即可选用。',
    providerFormSubtitleEdit: '修改渠道配置；保存后主进程会重启宿主以重新加载模型目录。',
    providerFieldName: '名称',
    providerFieldNameHint: '创建后不可改名（名称是 models.json 的键名）',
    providerFieldBaseUrl: 'Base URL',
    providerFieldBaseUrlHint: '服务端根地址，如 https://open.bigmodel.cn/api/paas/v4',
    providerFieldApi: 'API 格式',
    providerFieldApiHint: '按服务端接受的协议选择。',
    providerFieldKey: 'API 密钥',
    providerFieldKeyHint: '只保存在本机（加密存储），不会回显。',
    providerKeyKeepHint: '留空保持不变',
    providerKeyClear: '清除 key',
    providerKeyClearConfirm: '确认清除',
    providerKeyClearFailed: '清除失败，请重试。',
    providerModelsLabel: '模型',
    providerModelsHint: '模型 id 需与服务端一致；声明思考/视觉后会话中才会出现对应能力。',
    providerModelsEmpty: '还没有模型，先在下方添加一个。',
    providerModelAdd: '添加',
    providerModelRemove: '移除模型',
    providerSaved: '已保存',
    providerMeta: (apiLabel: string, count: number): string => `${apiLabel} · ${count} 个模型`,
    providerRemoveHint: (name: string): string => `删除渠道「${name}」？其 API key 一并删除。`,
    providerRemoveFailed: '删除失败，请重试。',
    providerBackToList: '渠道',
    modelThinkingOn: '已声明支持思考（点击关闭）',
    modelThinkingOff: '声明支持思考（点击开启）',
    modelVisionOn: '已声明支持视觉（点击关闭）',
    modelVisionOff: '声明支持视觉（点击开启；多模态模型必须打开，否则发送时图片被忽略）',
    keyPresent: '已保存 key',
    keyMissing: '缺少 key',
    save: '保存',
    remove: '移除',
    confirmRemove: '确认移除',
    formIncomplete: '名称、Base URL 和至少一个模型 id 必填。',
    formFailed: '保存失败，请检查后重试。',
    runtimeTitle: '运行状态',
    runtimeDesc: '系统监控、Worker 管理与诊断。分区打开期间实时轮询。',
    runtimeAttention: '注意：宿主未就绪或存在异常 worker',
    historyTitle: '历史',
    historyArchivedTitle: '已归档',
    historyRestore: '恢复',
    historyDesc: '恢复或管理已保存会话。',
    historyEmpty: '还没有已保存的会话。',
    historyFilterAll: '全部项目',
    historyFilter: (project: string): string => project,
    pin: '置顶',
    unpin: '取消置顶',
    revealInFinder: '在文件管理器中显示',
    historyMsgs: '条消息',
    refresh: '刷新',
    preferenceSaveFailed: '偏好保存失败，请重试。',
    permissionSaveFailed: '权限设置保存失败，请重试。',
    permissionsTitle: '权限',
    permissionsDesc: '新会话采用的默认权限模式与默认思考档。',
    permissionsDefaultMode: '默认权限模式',
    permissionsDefaultModeHint: '会话未显式选择时采用；修改不影响进行中的会话。',
    permissionsDefaultThinking: '默认思考档',
    permissionsDefaultThinkingHint: '新会话的 Off / Low / Medium / High；会话内设置优先。',
    permModeOptions: {
      plan: '计划',
      default: '默认',
      acceptEdits: '接受编辑',
      fullAuto: '全自动',
    },
    permissionsLoading: '正在加载权限设置…',
    agentsTitle: '智能体',
    agentsDesc: '会话可用的智能体定义。',
    agentsEmpty: '没有找到 agent 定义。',
    agentsUserBadge: '用户级',
    agentsProjectBadge: '项目级 · 仅受信可见',
    agentsTools: (count: number): string => (count === 1 ? '1 个工具' : `${count} 个工具`),
    agentsNew: '新建子智能体',
    agentsSearch: '搜索子智能体…',
    agentsFormTitleNew: '新建子智能体',
    agentsFormTitleEdit: '编辑子智能体',
    agentsFormSubtitleNew: '填写名称、工具和系统提示词，保存后返回列表。',
    agentsFormSubtitleEdit: '修改子智能体配置，保存后返回列表。',
    agentsGroupUser: '用户级',
    agentsGroupProject: '项目级',
    agentsCount: (count: number): string => (count === 1 ? '1 个' : `${count} 个`),
    agentsEditAction: '编辑',
    agentsRemoveAction: '删除',
    agentsConfirmRemove: '确认删除',
    agentsRemoveHint: (name: string): string => `删除定义 ${name}.md，运行中的子代理不受影响。`,
    agentsFieldName: '名称',
    agentsFieldNameHint: '调用名与文件名主干，kebab-case（小写字母、数字、连字符）。',
    agentsFieldDescription: '描述',
    agentsFieldDescriptionHint: '供主对话判断何时调用该 agent。',
    agentsFieldPrompt: '系统提示词',
    agentsFieldPromptHint: '该 agent 的职责、工具用法与返回格式。',
    agentsFieldModel: '模型',
    agentsModelInherit: '继承父级',
    agentsModelInheritHint: '运行时使用发起任务的对话模型。',
    agentsFieldTools: '工具',
    agentsToolsDefault: '全部工具',
    agentsToolsModeAll: '默认所有工具',
    agentsToolsModeCustom: '自定义工具',
    agentsToolsAllHint: '使用全部内置工具。',
    agentsToolsPickEmpty: '自定义工具需至少选择一个。',
    agentsFieldScope: '作用域',
    agentsScopeUser: '用户',
    agentsScopeUserHint: '全局配置，所有项目可用。',
    agentsScopeProject: '指定项目',
    agentsScopeProjectHint: '写入项目 .my-agent/agents，仅受信会话加载。',
    agentsScopeProjectNone: '选择项目',
    agentsSave: '保存',
    agentsCancel: '取消',
    agentsFormIncomplete: '名称与描述必填。',
    agentsNameInvalid: '名称须为 kebab-case：小写字母、数字与连字符，且以字母或数字开头（fork/main 为保留名）。',
    agentsNameExists: '同名 agent 已存在。',
    agentsSaveFailed: '保存失败，请重试。',
    agentsRemoveFailed: '删除失败，请重试。',
    skillsTitle: '技能',
    skillsDesc: '用户级技能的启用与关闭。',
    searchSkills: '搜索技能…',
    skillsEmpty: '未安装用户级技能。',
    skillsHint: '用户级技能来自 agent 技能目录；关闭的技能在会话中不可用（保存后自动重开活跃会话生效，进行中的生成会被中断）。项目级技能只在受信会话中出现。',
    skillsRefresh: '刷新',
    skillSourceOptions: {
      builtin: '内置',
      user: '用户',
      project: '项目',
    },
    skillDisabledHint: '已关闭：会话中不可用',
    skillToggleLabel: (name: string): string => `${name} 技能开关`,
    skillToggleFailed: '技能开关保存失败，请重试。',
    skillReopenFailed: '有会话重开失败，技能开关对它尚未生效。',
    generalTitle: '常规',
    generalDesc: '语言、外观与基础行为。',
    generalLanguage: '界面语言',
    generalLanguageHint: '界面与系统文案的显示语言。',
    appearanceLabel: '外观',
    appearanceLight: '浅色',
    appearanceDark: '深色',
    appearanceHint: '界面配色，即时生效。',
    generalTrustedDefault: '默认信任新项目',
    generalTrustedHint: '受信会话会加载工作目录中的项目扩展与项目级 agent。',
    generalIdleRecycle: '闲置自动回收',
    generalIdleRecycleHint: 'Worker 闲置超过该时长会被归档；会话再次使用时自动唤醒。',
    onboardingCardTitle: '引导',
    onboardingCardDesc: '重新运行新手引导：配置 Provider、选择默认模型并创建首个会话。',
    onboardingCardAction: '重新运行',
    generalSaveFailed: '保存失败，请重试。',
    generalDefaultModelInvalid: '默认模型已不可用；新会话将回落到首个可用模型。',
    defaultModelInvalidShort: '不可用',
    defaultModelTitle: '默认模型',
    defaultModelNone: '未设置（首个可用模型）',
    cancelEdit: '取消',
    testConnection: '测试连接',
    testing: '测试中…',
    testOk: (latencyMs: number): string => `正常 · ${latencyMs} ms`,
    testFailed: (reason: string): string => `失败（${reason}）`,
    providerModelEdit: '编辑模型',
    providerModelTest: '测试模型',
    modelDialogAddTitle: '添加模型',
    modelDialogEditTitle: '编辑模型',
    modelDialogFieldId: '模型 ID',
    modelDialogFieldIdPlaceholder: '模型 ID',
    modelDialogFieldContextWindow: '上下文窗口',
    modelDialogFieldContextWindowPlaceholder: '1000000',
    modelDialogFieldMaxTokens: '最大输出 Token',
    modelDialogFieldMaxTokensPlaceholder: '128000',
    modelDialogFieldInputTypes: '输入类型',
    modelDialogFieldOutputTypes: '输出类型',
    modelDialogInputText: '文本',
    modelDialogInputImage: '图片',
    modelDialogInputVideo: '视频',
    modelDialogInputPdf: 'PDF',
    modelDialogInputLocked: '始终开启',
    modelDialogUnsupported: '运行时尚不支持该模态',
    modelDialogCancel: '取消',
    modelDialogSave: '保存',
    modelDialogIdRequired: '请填写模型 ID',
    modelDialogIdDuplicate: '该模型 ID 已存在',
    modelDialogNumberInvalid: '请输入正整数（留空使用默认值）',
};
