/** 中文文案表（默认语言；key 结构与 en 表逐字段对齐，类型强制同步）。 */
import { zhSettings } from './zh-settings';
import type { en } from './en';
import {
  zhErrorCopy,
  imagesDeniedCopy,
  imagesTooManyCopy,
  noActiveSessionCopy,
  openEditorMissingCopy,
  resumeFailedCopy,
} from './zh-error-copy';

export const zh: typeof en = {
  appTitle: { name: 'Pai', suffix: 'Code' },
  sidebar: {
    search: '搜索',
    newTask: '新建任务',
    hotkeyNewTask: (modifier: string): string => `${modifier}N`,
    hotkeySearch: (modifier: string): string => `${modifier}K`,
    viewGrouped: '分组',
    viewProjects: '项目',
    pinnedSection: '已置顶',
    pinSession: '置顶',
    unpinSession: '取消置顶',
    showMore: '显示更多',
    working: '进行中',
    collapseSidebarHint: '收起侧栏',
    expandSidebarHint: '展开侧栏',
    settings: '设置',
    usage: '用量',
    automation: '自动化',
    runtimeAttention: '宿主或 worker 需要关注',
    retireSession: '回收 Worker',
    refresh: '刷新会话',
    closeSession: '关闭会话',
    renameSession: '重命名会话',
    renameFailed: '重命名失败，请重试。',
    clearSearch: '清空搜索',
    collapseGroup: '展开/折叠项目分组',
    noMatches: '没有匹配的会话',
    emptyTasks: (hotkey: string): string => `暂无任务，按 ${hotkey} 开始`,
    removeProject: '移除项目',
    viewProjectFiles: '查看项目文件',
    projectFilesEmpty: '没有可展示的文件',
    projectFilesLoading: '正在读取项目文件…',
    closeProjectFiles: '关闭',
    projectFilesCount: (count: number): string => `${count} 个文件`,
    age: {
      justNow: '刚刚',
      minutes: (value: number): string => `${value}分钟`,
      hours: (value: number): string => `${value}小时`,
      days: (value: number): string => `${value}天`,
    },
  },
  thread: {
    toggleMaximize: '切换最大化',
    openDiff: '打开 Diff',
    turnFailedLabel: '请求失败',
    turnAbortedLabel: '已中止',
    openMenu: ['在访达中打开', '在终端中打开', '在编辑器中打开'] as [string, string, string],
    copyPath: '复制路径',
    projectMenuAria: '项目操作',
    toggleSplitView: '切换分栏',
    sessionMenuAria: '会话操作',
    sessionRename: '重命名',
    sessionCopyId: '复制会话 ID',
    sessionClose: '关闭会话',
    sessionArchive: '归档会话',
    renameTitleAria: '重命名会话',
    statusAria: '会话状态',
    status: {
      idle: '空闲',
      running: '运行中',
      permission: '等待权限',
      compacting: '压缩中',
      queued: '排队中',
    },
    openFailed: (reason: string): string => `打开失败（${reason}）。`,
    openEditorMissing: openEditorMissingCopy,
    copyFailed: '复制失败，请重试。',
    emptyTitle: '还没有消息',
    retryHydration: '重试加载',
    emptyHint: '描述一个改动、一个问题或一个任务，即可开始。',
    /** 无会话空舞台（工作区无任何会话）：输入卡的全部会话域动作都无定址目标 */
    noSessionTitle: '还没有会话',
    noSessionHint: '新建任务（⌘N）开始第一段对话。',
    reloadTrusted: '以受信模式重开',
    reloadUntrusted: '以非受信模式重开',
    reloadTrustFailed: '重开会话失败，请重试。',
  },
  palette: {
    aria: '命令面板',
    placeholder: '搜索操作、会话、文件、命令…',
    empty: '没有匹配项',
    groups: {
      actions: '操作',
      sessions: '会话',
      files: '文件',
      commands: '命令',
      settings: '设置',
    },
    actions: {
      newTask: '新建任务',
      openDiff: '打开 Diff 面板',
      openAgents: '打开子代理面板',
      openFinder: '在访达中打开',
      openTerminal: '在终端中打开',
      openEditor: '在编辑器中打开',
      copyPath: '复制项目路径',
      copySessionId: '复制会话 ID',
      closeSession: '关闭当前会话',
      openSettings: '打开设置',
      openUsage: '打开用量',
    },
  },
  panel: {
    tabDiff: 'Diff',
    tabAgents: '子代理',
    close: '收起面板',
    closeTab: (label: string): string => `关闭 ${label}`,
    file: {
      loading: '正在读取…',
      refresh: '刷新',
      preview: '预览',
      source: '源码',
      modeAria: '切换显示模式',
      truncated: '文件超过 2 MiB，已截断显示。',
      errors: {
        notFound: '文件不存在或已被删除。',
        binary: '二进制文件不支持预览。',
        invalidParams: '该路径不支持打开。',
        pathForbidden: '该路径不在当前项目内。',
        cwdForbidden: '当前目录不可访问。',
        cwdNotFound: '当前目录不存在。',
        readFailed: '读取失败，请重试。',
      },
    },
  },
  flow: {
    openDiff: '打开 Diff',
    steerPlaceholder: '向该子智能体注入指令…',
    steerFailed: (reason: string): string => `改向失败（${reason}）。`,
    /** 思考档词表外值（hub 静默忽略——渲染层先行拒绝提示） */
    thinkingInvalid: '该思考档不可用。',
    /** 思考档写入被 hub 拒绝（reason 为 hub 错误文案） */
    thinkingRejected: (reason: string): string => `思考档未应用：${reason}。`,
    /** 会话域写动作无定址目标（工作区无任何会话时的空舞台） */
    noActiveSession: noActiveSessionCopy,
    /** 会话模型切换被 hub 拒绝（reason 为 hub 错误文案） */
    modelRejected: (reason: string): string => `模型未切换：${reason}。`,
    /** 子代理状态词（running|idle|stopped → 工作中/空闲/已归档） */
    subagentBusy: '工作中',
    subagentIdle: '空闲',
    subagentArchived: '已归档',
    subagentFailed: '失败',
    /** 子代理权限请求信息行（协议无应答命令，hub 到期自动拒绝） */
    subagentAskPending: (toolName: string): string => `等待确认（${toolName}），超时自动拒绝`,
    workingFor: '已工作',
    workedFor: '共工作',
    captionMinimize: '最小化',
    captionMaximize: '最大化',
    captionRestore: '还原',
    captionClose: '关闭',
    agentsWorking: (count: number): string => `${count} 个子智能体工作中，打开 Agents 面板`,
    changedFiles: (count: number): string => (count === 1 ? '1 个文件变更' : `${count} 个文件变更`),
    toggleAgents: '切换子智能体面板',
    toggleDiff: '切换 Diff 面板',
    agentsPanelEmpty: '尚未派生子智能体',
    diffPanelEmpty: '本会话暂无文件变更',
    executing: '正在执行…',
    toolStopped: '已停止',
    toolRunning: '运行中',
    /** 执行单元类型标签（未知工具直接显示工具名） */
    labelBash: '命令',
    labelRead: '读取',
    labelEdit: '编辑',
    labelWrite: '写入',
    labelSearch: '搜索',
    labelList: '列目录',
    labelSubagent: '子智能体',
    /** 思考单元收起态标签（运行中同显 思考，运行态由脉冲点区分） */
    thought: '思考',
    turnStoppedSummary: (elapsed: string): string => `已停止 · ${elapsed}`,
    /** 历史轮左缘锚点（无障碍名） */
    turnAnchorAria: (time: string): string => `查看 ${time} 结束的轮次`,
    /** 历史轮锚点带（无障碍名） */
    turnAnchorRailAria: '历史轮次导航',
    thinking: '思考',
    queued: (count: number): string => (count === 1 ? '1 条排队消息' : `${count} 条排队消息`),
    retrying: (attempt: number): string => `重试中（第 ${attempt} 次）`,
    crashedBanner: '本会话的执行进程已退出。发送消息将恢复会话并继续。',
    hydrateFailedTitle: '历史加载失败',
    hydrateFailedHint: '未能读取该会话的历史记录，可重试。',
    compacting: '正在压缩上下文…',
    bashRunning: '正在执行命令…',
    bashFailed: (reason: string): string => `命令未执行（${reason}）。`,
    editRerun: '编辑并重开（分叉）',
    retryFromHere: '从这里重试',
    forkFailed: '分叉会话失败，请重试。',
    /** 流式中的 fork 被 hub 拒绝（thread is streaming）：先停止会话再分叉 */
    forkStreaming: '会话正在回复中，请先停止会话再分叉。',
    /** 回合结算失败（settled ok=false；reason 为 hub/worker 错误文案） */
    turnFailed: (reason: string): string => (reason.length > 0 ? `本轮回复失败（${reason}）。` : '本轮回复失败。'),
    forkedImageName: (index: number): string => `图片 ${index}`,
    resumeFailed: resumeFailedCopy,
    stopConfirmTitle: '停止全部任务？',
    stopConfirmHint: '将终止全部前台与后台子智能体，且不可恢复。',
    stopConfirmYes: '全部停止',
    stopConfirmNo: '取消',
    bashNoImages: '直执行命令不支持携带图片，请移除附件或改用消息发送。',
    imagesDenied: imagesDeniedCopy,
    imagesTooMany: imagesTooManyCopy,
    systemMessageLabel: '系统',
    sendFailed: (reason: string): string => `消息未发送（${reason}），请重试。`,
    toolFailed: (exitCode: number): string => `退出码 ${exitCode}`,
    copyMessage: '复制消息',
    editMessage: '编辑消息',
    scrollToBottom: '回到底部',
    copyCommand: '复制命令',
    copyOutput: '复制输出',
    copied: '已复制',
    outputLabel: '输出',
    toggleOutput: '展开/收起命令输出',
    panelWorking: (count: number): string => (count === 1 ? '1 个进行中' : `${count} 个进行中`),
    panelSettled: (count: number): string => (count === 1 ? '1 个已完成' : `${count} 个已完成`),
    footerTokens: (tokens: string): string => `Σ ${tokens} tok`,
    metaTokens: (tokens: string | null): string => (tokens === null ? '— tok' : `${tokens} tok`),
    metaTools: (count: number): string | null => {
      if (count <= 0) return null;
      return count === 1 ? '1 个工具' : `${count} 个工具`;
    },
  },
  composer: {
    placeholder: '随便问；@ 引用文件，/ 选择命令或技能',
    queuePlaceholder: '继续输入以排队后续修改',
    sendNow: '立即',
    editQueued: '编辑排队消息',
    removeQueued: '移除排队消息',
    attach: '添加图片与文件',
    send: '发送消息',
    stop: '停止生成',
    usageSummary: '用量',
    steerPlaceholder: '向该子智能体注入指令…',
    steerFailed: (reason: string): string => `改向失败（${reason}）。`,
    noModels: '还没有模型——去设置添加',
    hostDownModels: '宿主未连接——模型暂不可选',
    effortDefault: '默认',
    slashAria: '命令建议',
    fileAria: '文件建议',
    groupCommands: '命令',
    groupSkills: '技能',
    groupFiles: '文件',
    slashHint: '输入内容以搜索命令或技能',
    scrollDown: '向下滚动',
    permissionMode: '权限模式',
    imageUnsupported: '只能附加不超过 20 MB 的常见格式图片（发送前会自动压缩）。',
    removeImage: '移除图片',
    projectSegment: '工作目录',
    branchSegment: '当前分支',
    branchLoading: '读取分支…',
    branchUnavailable: '分支不可用',
    notARepo: '非 git 仓库',
    detachedHead: '游离 HEAD',
  },
  dialogs: {
    confirmTitle: '需要确认',
    allow: '允许',
    deny: '拒绝',
    cancel: '取消',
    morePending: (count: number): string => (count === 1 ? '还有 1 个请求等待' : `还有 ${count} 个请求等待`),
    fromSubagent: (agent: string): string => `子智能体请求 · ${agent}`,
  },
  settings: zhSettings,
  newTask: {
    greetingNight: '夜深了',
    greetingMorning: '早上好',
    greetingAfternoon: '下午好',
    greetingEvening: '晚上好',
    subtitleNight: '还在忙什么？',
    subtitleMorning: '今天想构建点什么？',
    subtitleAfternoon: '接下来推进什么？',
    subtitleEvening: '今晚想构建点什么？',
    placeholder: '向 pai 提问，@ 添加上下文，/ 选择命令或技能',
    quickTasks: ['了解这个项目', '修复构建失败', '补充单元测试', '审查最近的改动'],
    quickTaskPrompt: (label: string): string => `请帮我${label}`,
    workspacePickerTitle: '选择工作区',
    workspaceSearch: '搜索文件夹',
    workspaceEmpty: '没有匹配的文件夹',
    openFolder: '打开文件夹…',
    trustedLabel: '信任此项目',
    trustedHint: '受信会话会加载项目扩展与项目级 agent。只对你拥有并审阅过的仓库开启。',
    pickFailed: '目录选择器打开失败，请重试。',
  },
  branch: {
    /** 分支面板（两页共用）：可访问名 + 列表分组标题。 */
    panelTitle: '分支',
    search: '搜索分支',
    empty: '没有匹配的分支',
    loading: '正在读取分支…',
    unavailable: '分支列表读取失败，请重试。',
    dirtyFiles: (count: number): string => `未提交的更改：${count} 个文件`,
    createBranch: '创建并检出新分支…',
    openGraph: 'Git 图谱',
    createTitle: '创建并检出新分支',
    createSubtitle: '基于当前 HEAD 创建一个新的本地分支，并在创建成功后立即切换过去。',
    createFieldLabel: '分支名',
    createFieldPlaceholder: '例如 feature/git-branch-switcher',
    createHelper: '仅支持基于当前 HEAD 创建并切换。',
    createSubmit: '创建并切换',
  },
  gitGraph: {
    title: 'Git 图谱',
    colGraph: '图',
    colDescription: '描述',
    colDate: '日期',
    colAuthor: '作者',
    colCommit: '提交',
    refresh: '刷新',
    close: '关闭',
    loading: '提交加载中…',
    unavailable: '图谱加载失败，请重试。',
    empty: '这个仓库还没有提交。',
    truncated: (count: number): string => `仅显示最近 ${count} 条提交`,
    headLabel: 'HEAD',
  },
  notices: {
    dismiss: '关闭',
  },
  usage: {
    title: '用量',
    close: '关闭',
    inputTokens: '输入 tokens',
    outputTokens: '输出 tokens',
    tokensLabel: 'tokens',
    costLabel: '费用',
    messagesLabel: '消息',
    toolCallsLabel: '工具调用',
    totalTokens: '总 tokens',
    totalCost: '总费用',
    sessionsCount: (count: number): string => (count === 1 ? '1 个会话' : `${count} 个会话`),
    byProject: '按项目',
    topSessions: '会话排行',
    empty: '暂无带用量数据的活跃会话。',
    liveOnlyHint: '仅统计本次运行中的活跃会话；跨重启的用量历史暂未记录。',
  },
  runtime: {
    title: '运行状态',
    close: '关闭',
    healthLabel: '宿主健康',
    healthHealthy: '健康',
    healthDegraded: '注意',
    healthFailed: '故障',
    autoRefresh: '自动刷新',
    hostPhase: '宿主相位',
    phaseStarting: '启动中',
    phaseReady: '就绪',
    phaseRestarting: '重启中',
    phaseFailed: '已失败',
    heartbeat: '心跳',
    heartbeatAgo: (seconds: number): string => `${seconds} 秒前`,
    heartbeatNever: '尚未收到心跳',
    uptime: '运行时长',
    restarts: '重启',
    versions: '版本',
    bunLabel: 'Bun',
    pidLabel: 'PID',
    neverRestarted: '从未',
    capacity: 'Worker',
    stateLive: '活跃',
    executing: '执行中',
    idle: '空闲',
    parked: '已归档',
    dead: '异常',
    limit: '上限',
    memory: '内存',
    systemMemory: '系统',
    appMemory: '应用',
    hubMemory: '宿主',
    workersMemory: 'Worker',
    cpu: 'CPU',
    resourceTrend: '资源走势',
    workersTitle: 'Workers',
    filterAll: '全部',
    filterExecuting: '执行中',
    filterIdle: '空闲',
    filterParked: '已归档',
    filterDead: '异常',
    columnSession: '会话',
    columnState: '状态',
    columnIdle: '空闲',
    columnModel: '模型',
    columnQueue: '排队',
    columnTokens: 'Tokens',
    columnMemory: '内存',
    columnActions: '操作',
    rowMenu: '更多操作',
    recyclePolicy: '自动回收',
    recycleAllIdle: '回收全部空闲',
    minutesOption: (minutes: number): string => `${minutes} 分钟`,
    idleFor: (minutes: number): string => `空闲 ${minutes} 分钟`,
    recycleIn: (seconds: number): string => `${seconds} 秒后回收`,
    manual: '手动',
    actionStop: '停止',
    actionRecycle: '回收',
    actionForceRecycle: '强制回收',
    actionOpen: '打开',
    keepaliveOn: '常驻',
    keepaliveOff: '取消常驻',
    rssRetireLimit: 'RSS 回收阈值',
    rssRetireOff: '未启用',
    timeline: '事件',
    timelineEmpty: '暂无事件记录。',
    stderr: '宿主 stderr（尾部）',
    stderrLoad: '加载 stderr',
    stderrEmpty: '暂未捕获 stderr 输出。',
    copySummary: '复制摘要',
    summaryCopyFailed: '复制失败',
    summaryTitle: 'Pai 运行状态摘要',
    summaryThreads: (live: number, parked: number, dead: number): string => `${live} 活跃 · ${parked} 已归档 · ${dead} 异常`,
    summaryCopied: '摘要已复制',
    exportBundle: '导出诊断包',
    exported: '诊断包已导出并定位',
    restartHost: '重启宿主',
    hostUnavailable: '宿主不可用——排障起点',
    noWorkers: '暂无会话',
    emptyHistory: '正在采集资源样本…',
    fetchFailed: '运行状态快照拉取失败——请确认应用进程为最新版本（重启应用）；切换分区可重试。',
    recycleFailed: '回收失败',
    keepaliveFailed: '常驻设置失败',
    recycleSettingFailed: '回收档位设置失败',
    exportFailed: '导出失败',
  },
  onboarding: {
    title: '欢迎使用 pai',
    hint: '连接一个 Provider 并选择模型即可开始。也可以跳过，稍后在设置中配置。',
    stepProvider: '连接 Provider',
    stepModel: '选择默认模型',
    stepCwd: '选择工作目录',
    cwdField: '/path/to/your/project',
    next: '下一步',
    back: '上一步',
    finish: '开始对话',
    skip: '跳过配置',
    noModelsYet: '还没有模型。完成 Provider 配置或刷新。',
    refreshModels: '刷新',
  },
  bootstrap: {
    loadingTitle: '正在启动…',
    loadingHint: '正在连接 coding agent 宿主。',
    failedTitle: '无法启动',
    bridgeHint: '预加载桥不可用。请从桌面入口重新启动应用。',
    hostFailed: 'agent 宿主启动失败。请在设置中检查 Provider 配置与 host-hub 路径。',
  },
  host: {
    downBanner: 'agent 宿主未连接，模型与会话暂不可用（已配置的 Provider 不受影响）。',
    downAction: '打开设置',
  },
  markdown: {
    copyCode: '复制代码',
    downloadDiagram: '下载图示',
    downloadDiagramSvg: '下载图示为 SVG',
    downloadDiagramPng: '下载图示为 PNG',
    downloadDiagramMmd: '下载图示为 MMD',
    viewFullscreen: '全屏查看',
    exitFullscreen: '退出全屏',
    mermaidFormatSvg: 'SVG',
    mermaidFormatPng: 'PNG',
    mermaidFormatMmd: 'MMD',
    zoomIn: '放大',
    zoomOut: '缩小',
    resetView: '重置缩放与平移',
    copyTable: '复制表格',
    copyTableAsMarkdown: '复制表格为 Markdown',
    copyTableAsCsv: '复制表格为 CSV',
    copyTableAsTsv: '复制表格为 TSV',
    downloadTable: '下载表格',
    downloadTableCsv: '下载表格为 CSV',
    downloadTableMarkdown: '下载表格为 Markdown',
    tableFormatMarkdown: 'Markdown',
    tableFormatCsv: 'CSV',
    tableFormatTsv: 'TSV',
    imageNotAvailable: '图片不可用',
    downloadImage: '下载图片',
    openExternalLink: '打开外部链接？',
    externalLinkWarning: '即将访问外部网站。',
    close: '关闭',
    copyLink: '复制链接',
    copied: '已复制',
    openLink: '打开链接',
  },
  modelPicker: {
    title: '选择模型',
    searchPlaceholder: '搜索模型…',
    empty: '没有匹配的模型',
  },
  errorCopy: zhErrorCopy,
};
