/** 中文文案表（默认语言；key 结构与 en 表逐字段对齐，类型强制同步）。 */
import { zhSettings } from './zh-settings';
import type { en } from './en';

export const zh: typeof en = {
  appTitle: { name: 'Pai', suffix: 'Code' },
  sidebar: {
    search: '搜索',
    newTask: '新建任务',
    automation: '自动化',
    pluginMarket: '插件市场',
    hotkeyNewTask: (modifier: string): string => `${modifier}N`,
    hotkeySearch: (modifier: string): string => `${modifier}K`,
    viewGrouped: '分组',
    viewProjects: '项目',
    pinnedSection: '已置顶',
    pinSession: '置顶',
    unpinSession: '取消置顶',
    showMore: '显示更多',
    working: '进行中',
    collapseSidebarHint: '收起侧栏',
    toggleSidebar: '切换侧栏',
    settings: '设置',
    workflows: '工作流',
    usage: '用量',
    refresh: '刷新会话',
    closeSession: '关闭会话',
    renameSession: '重命名会话',
    renameFailed: '重命名失败，请重试。',
    clearSearch: '清空搜索',
    collapseGroup: '展开/折叠项目分组',
    noMatches: '没有匹配的会话',
    emptyTasks: (hotkey: string): string => `暂无任务，按 ${hotkey} 开始`,
    removeProject: '移除项目',
    viewProjectFiles: '查看项目文件',
    projectFilesEmpty: '没有可展示的文件',
    projectFilesLoading: '正在读取项目文件…',
    closeProjectFiles: '关闭',
    projectFilesCount: (count: number): string => `${count} 个文件`,
    age: {
      justNow: '刚刚',
      minutes: (value: number): string => `${value}分钟`,
      hours: (value: number): string => `${value}小时`,
      days: (value: number): string => `${value}天`,
    },
  },
  thread: {
    addAction: '更多操作',
    open: '打开',
    commitPushPr: '提交、推送并建 PR',
    toggleSplitView: '切换分栏',
    toggleMaximize: '切换最大化',
    tabAdd: '添加面板',
    openDiff: '打开 Diff',
    turnFailedLabel: '请求失败',
    turnAbortedLabel: '已中止',
    openMenu: ['在访达中打开', '在终端中打开', '在编辑器中打开'],
    commitMenu: ['仅提交', '创建 Pull Request', '推送到远端'],
    emptyTitle: '还没有消息',
    retryHydration: '重试加载',
    emptyHint: '描述一个改动、一个问题或一个任务，即可开始。',
    reloadTrusted: '以受信模式重开',
    reloadUntrusted: '以非受信模式重开',
    reloadTrustFailed: '重开会话失败，请重试。',
  },
  flow: {
    openDiff: '打开 Diff',
    closeDiffPanel: '关闭 Diff 面板',
    steerPlaceholder: '向该子代理注入指令…',
    steerFailed: (reason: string): string => `改向失败（${reason}）。`,
    workingFor: '已工作',
    workedFor: '共工作',
    captionMinimize: '最小化',
    captionMaximize: '最大化',
    captionRestore: '还原',
    captionClose: '关闭',
    agentsWorking: (count: number): string => `${count} 个子代理工作中，打开 Agents 面板`,
    changedFiles: (count: number): string => (count === 1 ? '1 个文件变更' : `${count} 个文件变更`),
    closeAgents: '关闭子代理面板',
    toggleAgents: '切换子代理面板',
    toggleDiff: '切换 Diff 面板',
    panelTitle: '直接派生',
    agentsPanelEmpty: '尚未派生子代理',
    diffPanelTitle: '文件变更',
    diffPanelEmpty: '本会话暂无文件变更',
    statusWorking: '工作中',
    executing: '正在执行…',
    toolStopped: '已停止',
    toolRunning: '运行中',
    /** 执行单元类型标签（未知工具直接显示工具名） */
    labelBash: '命令',
    labelRead: '读取',
    labelEdit: '编辑',
    labelWrite: '写入',
    labelSearch: '搜索',
    labelList: '列目录',
    labelSubagent: '子代理',
    /** 思考单元收起态标签（运行中同显 思考，运行态由脉冲点区分） */
    thought: '思考',
    turnStoppedSummary: (elapsed: string): string => `已停止 · ${elapsed}`,
    /** 历史轮左缘锚点（无障碍名） */
    turnAnchorAria: (time: string): string => `查看 ${time} 结束的轮次`,
    /** 历史轮锚点带（无障碍名） */
    turnAnchorRailAria: '历史轮次导航',
    thinking: '思考',
    queued: (count: number): string => (count === 1 ? '1 条排队消息' : `${count} 条排队消息`),
    retrying: (attempt: number, maxAttempts: number): string => `重试中（${attempt}/${maxAttempts}）`,
    crashedBanner: '本会话的执行进程已退出。发送消息将恢复会话并继续。',
    hydrateFailedTitle: '历史加载失败',
    hydrateFailedHint: '未能读取该会话的历史记录，可重试。',
    compacting: '正在压缩上下文…',
    bashRunning: '正在执行命令…',
    bashFailed: (reason: string): string => `命令未执行（${reason}）。`,
    editRerun: '编辑并重开（分叉）',
    retryFromHere: '从这里重试',
    forkFailed: '分叉会话失败，请重试。',
    forkCancelled: '分叉被扩展拦截，会话未变化。',
    forkedImageName: (index: number): string => `图片 ${index}`,
    resumeFailed: '会话恢复失败，请重试。',
    stopConfirmTitle: '停止全部任务？',
    stopConfirmHint: '将终止全部前台与后台子代理，且不可恢复。',
    stopConfirmYes: '全部停止',
    stopConfirmNo: '取消',
    bashNoImages: '直执行命令不支持携带图片，请移除附件或改用消息发送。',
    systemMessageLabel: '系统',
    sendFailed: (reason: string): string => `消息未发送（${reason}），请重试。`,
    toolFailed: (exitCode: number): string => `退出码 ${exitCode}`,
    copyMessage: '复制消息',
    editMessage: '编辑消息',
    scrollToBottom: '回到底部',
    copyCommand: '复制命令',
    copyOutput: '复制输出',
    copied: '已复制',
    outputLabel: '输出',
    toggleOutput: '展开/收起命令输出',
    panelWorking: (count: number): string => (count === 1 ? '1 个进行中' : `${count} 个进行中`),
    panelSettled: (count: number): string => (count === 1 ? '1 个已完成' : `${count} 个已完成`),
    footerTokens: (tokens: string): string => `Σ ${tokens} tok`,
    metaTokens: (tokens: string | null): string => (tokens === null ? '— tok' : `${tokens} tok`),
    metaTools: (count: number): string | null => {
      if (count <= 0) return null;
      return count === 1 ? '1 个工具' : `${count} 个工具`;
    },
  },
  composer: {
    placeholder: '随便问；@ 引用文件，$ 使用技能，/ 选择命令',
    queuePlaceholder: '继续输入以排队后续修改',
    sendNow: '立即',
    editQueued: '编辑排队消息',
    removeQueued: '移除排队消息',
    attach: '添加图片与文件',
    send: '发送消息',
    stop: '停止生成',
    contextUsage: '上下文占用',
    steerPlaceholder: '向该子代理注入指令…',
    steerFailed: (reason: string): string => `改向失败（${reason}）。`,
    noModels: '还没有模型——去设置添加',
    hostDownModels: '宿主未连接——模型暂不可选',
    effortUnavailable: '思考不可用',
    effortDefault: '默认',
    slashAria: '命令建议',
    fileAria: '文件建议',
    groupCommands: '命令',
    groupSkills: '技能',
    groupFiles: '文件',
    slashHint: '输入内容以搜索命令或技能',
    scrollDown: '向下滚动',
    permissionMode: '权限模式',
    imageUnsupported: '只能附加不超过 20 MB 的常见格式图片（发送前会自动压缩）。',
    removeImage: '移除图片',
    projectSegment: '工作目录',
    branchSegment: '当前分支',
    branchLoading: '读取分支…',
    branchUnavailable: '分支不可用',
    notARepo: '非 git 仓库',
    detachedHead: '游离 HEAD',
    effortMenu: ['低 · 200K', '中 · 200K', '高 · 1M'],
  },
  dialogs: {
    confirmTitle: '需要确认',
    selectTitle: '请选择',
    inputTitle: '需要输入',
    allow: '允许',
    deny: '拒绝',
    cancel: '取消',
    send: '提交',
    noOptions: '没有可选项',
    morePending: (count: number): string => (count === 1 ? '还有 1 个请求等待' : `还有 ${count} 个请求等待`),
    fromSubagent: (agent: string): string => `子代理请求 · ${agent}`,
  },
  settings: zhSettings,
  newTask: {
    greetingNight: '夜深了',
    greetingMorning: '早上好',
    greetingAfternoon: '下午好',
    greetingEvening: '晚上好',
    subtitleNight: '还在忙什么？',
    subtitleMorning: '今天想构建点什么？',
    subtitleAfternoon: '接下来推进什么？',
    subtitleEvening: '今晚想构建点什么？',
    placeholder: '向 pai 提问，使用 @ 添加上下文',
    quickTasks: ['了解这个项目', '修复构建失败', '补充单元测试', '审查最近的改动'],
    quickTaskPrompt: (label: string): string => `请帮我${label}`,
    workspacePickerTitle: '选择工作区',
    workspaceSearch: '搜索文件夹',
    workspaceEmpty: '没有匹配的文件夹',
    openFolder: '打开文件夹…',
    trustedLabel: '信任此项目',
    trustedHint: '受信会话会加载项目扩展与项目级 agent。只对你拥有并审阅过的仓库开启。',
    branchPickerTitle: '切换分支',
    branchSearch: '搜索分支',
    branchEmpty: '没有匹配的分支',
    createBranch: '创建并检出…',
    createBranchTitle: (from: string): string => `从 ${from} 创建并检出`,
    createBranchField: '新分支名称',
    createBranchSubmit: '创建并检出',
    branchLoading: '正在读取分支…',
    branchUnavailable: '分支列表读取失败，请重试。',
    branchFailed: (reason: string): string => {
      if (reason === 'branch_exists') return '同名分支已存在，换一个名称。';
      if (reason === 'invalid_branch') return '分支名不合法，请换个名称。';
      if (reason === 'dirty_worktree') return '工作区有未提交改动，先提交或暂存后再切换分支。';
      if (reason === 'unknown_branch') return '目标分支不存在，请刷新后重试。';
      if (reason === 'not_a_repo') return '该目录不是 git 仓库。';
      if (reason === 'git_unavailable') return '系统未找到 git 命令，无法操作分支。';
      if (reason === 'cwd_not_found') return '工作目录不存在，可能已被移动或删除。';
      return `分支操作失败（${reason}）。`;
    },
    pickFailed: '目录选择器打开失败，请重试。',
    createFailed: (reason: string): string => {
      if (reason === 'host_unavailable') return 'agent 宿主未就绪（正在启动或重启），请稍后重试。';
      if (reason.startsWith('Model not found')) return '所选模型不可用，请在设置中检查 Provider 配置。';
      if (/cwd|directory|absolute|exist/i.test(reason)) return '无法开始会话，请检查目录后重试。';
      return `无法开始会话（${reason}），请重试。`;
    },
  },
  notices: {
    dismiss: '关闭',
  },
  usage: {
    title: '用量',
    close: '关闭',
    contextLabel: '上下文',
    tokensLabel: 'tokens',
    costLabel: '费用',
    messagesLabel: '消息',
    toolCallsLabel: '工具调用',
    totalTokens: '总 tokens',
    totalCost: '总费用',
    sessionsCount: (count: number): string => (count === 1 ? '1 个会话' : `${count} 个会话`),
    byProject: '按项目',
    topSessions: '会话排行',
    empty: '暂无带用量数据的活跃会话。',
    liveOnlyHint: '仅统计本次运行中的活跃会话；跨重启的用量历史暂未记录。',
  },
  onboarding: {
    title: '欢迎使用 pai',
    hint: '连接一个 Provider 并选择模型即可开始。也可以跳过，稍后在设置中配置。',
    stepProvider: '连接 Provider',
    stepModel: '选择默认模型',
    stepCwd: '选择工作目录',
    cwdField: '/path/to/your/project',
    next: '下一步',
    back: '上一步',
    finish: '开始对话',
    skip: '跳过配置',
    noModelsYet: '还没有模型。完成 Provider 配置或刷新。',
    refreshModels: '刷新',
  },
  bootstrap: {
    loadingTitle: '正在启动…',
    loadingHint: '正在连接 coding agent 宿主。',
    failedTitle: '无法启动',
    bridgeHint: '预加载桥不可用。请从桌面入口重新启动应用。',
    hostFailed: 'agent 宿主启动失败。请在设置中检查 Provider 配置与 pai-cli 路径。',
  },
  host: {
    downBanner: 'agent 宿主未连接，模型与会话暂不可用（已配置的 Provider 不受影响）。',
    downAction: '打开设置',
  },
  markdown: {
    copyCode: '复制代码',
    downloadDiagram: '下载图示',
    downloadDiagramSvg: '下载图示为 SVG',
    downloadDiagramPng: '下载图示为 PNG',
    downloadDiagramMmd: '下载图示为 MMD',
    viewFullscreen: '全屏查看',
    exitFullscreen: '退出全屏',
    mermaidFormatSvg: 'SVG',
    mermaidFormatPng: 'PNG',
    mermaidFormatMmd: 'MMD',
    zoomIn: '放大',
    zoomOut: '缩小',
    resetView: '重置缩放与平移',
    copyTable: '复制表格',
    copyTableAsMarkdown: '复制表格为 Markdown',
    copyTableAsCsv: '复制表格为 CSV',
    copyTableAsTsv: '复制表格为 TSV',
    downloadTable: '下载表格',
    downloadTableCsv: '下载表格为 CSV',
    downloadTableMarkdown: '下载表格为 Markdown',
    tableFormatMarkdown: 'Markdown',
    tableFormatCsv: 'CSV',
    tableFormatTsv: 'TSV',
    imageNotAvailable: '图片不可用',
    downloadImage: '下载图片',
    openExternalLink: '打开外部链接？',
    externalLinkWarning: '即将访问外部网站。',
    close: '关闭',
    copyLink: '复制链接',
    copied: '已复制',
    openLink: '打开链接',
  },
  modelPicker: {
    title: '选择模型',
    searchPlaceholder: '搜索模型…',
    empty: '没有匹配的模型',
  },
};
