/** 中文文案表（默认语言；key 结构与 en 表逐字段对齐，类型强制同步）。 */
import type { en } from './en';

export const zh: typeof en = {
  appTitle: { name: 'T3', suffix: 'Code' },
  sidebar: {
    search: '搜索',
    newTask: '新建任务',
    automation: '自动化',
    pluginMarket: '插件市场',
    hotkeyNewTask: (modifier: string): string => `${modifier}N`,
    hotkeySearch: (modifier: string): string => `${modifier}K`,
    viewGrouped: '分组',
    viewProjects: '项目',
    pinnedSection: '已置顶',
    pinSession: '置顶',
    unpinSession: '取消置顶',
    showMore: '显示更多',
    working: '进行中',
    collapseSidebarHint: '收起侧栏',
    toggleSidebar: '切换侧栏',
    settings: '设置',
    workflows: '工作流',
    usage: '用量',
    refresh: '刷新会话',
    closeSession: '关闭会话',
    renameSession: '重命名会话',
    renameFailed: '重命名失败，请重试。',
    clearSearch: '清空搜索',
    collapseGroup: '展开/折叠项目分组',
    noMatches: '没有匹配的会话',
    emptyTasks: (hotkey: string): string => `暂无任务，按 ${hotkey} 开始`,
    removeProject: '移除项目',
    viewProjectFiles: '查看项目文件',
    projectFilesEmpty: '没有可展示的文件',
    projectFilesLoading: '正在读取项目文件…',
    closeProjectFiles: '关闭',
    projectFilesCount: (count: number): string => `${count} 个文件`,
    age: {
      justNow: '刚刚',
      minutes: (value: number): string => `${value}分钟`,
      hours: (value: number): string => `${value}小时`,
      days: (value: number): string => `${value}天`,
    },
  },
  thread: {
    addAction: '更多操作',
    open: '打开',
    commitPushPr: '提交、推送并建 PR',
    toggleSplitView: '切换分栏',
    toggleMaximize: '切换最大化',
    tabAdd: '添加面板',
    openDiff: '打开 Diff',
    openAgents: '打开 Agents',
    turnFailedLabel: '请求失败',
    turnAbortedLabel: '已中止',
    openMenu: ['在访达中打开', '在终端中打开', '在编辑器中打开'],
    commitMenu: ['仅提交', '创建 Pull Request', '推送到远端'],
    emptyTitle: '还没有消息',
    emptyHint: '描述一个改动、一个问题或一个任务，即可开始。',
    reloadTrusted: '以受信模式重开',
    reloadUntrusted: '以非受信模式重开',
    reloadTrustFailed: '重开会话失败，请重试。',
  },
  flow: {
    openDiff: '打开 Diff',
    openAgents: '打开 Agents',
    closeDiffPanel: '关闭 Diff 面板',
    steerPlaceholder: '向该子代理注入指令…',
    steerFailed: (reason: string): string => `改向失败（${reason}）。`,
    workingFor: '已工作',
    workedFor: '共工作',
    captionMinimize: '最小化',
    captionMaximize: '最大化',
    captionRestore: '还原',
    captionClose: '关闭',
    subagentsSummary: (count: number): string => (count === 1 ? '启动了 1 个子代理' : `启动了 ${count} 个子代理`),
    changedFiles: (count: number): string => (count === 1 ? '1 个文件变更' : `${count} 个文件变更`),
    closeAgents: '关闭子代理面板',
    toggleAgents: '切换子代理面板',
    toggleDiff: '切换 Diff 面板',
    panelTitle: '直接派生',
    agentsPanelEmpty: '尚未派生子代理',
    diffPanelTitle: '文件变更',
    diffPanelEmpty: '本会话暂无文件变更',
    statusWorking: '工作中',
    executing: '正在执行…',
    toolStopped: '已停止',
    toolRunning: '运行中',
    /** 执行单元类型标签（未知工具直接显示工具名） */
    labelBash: '命令',
    labelRead: '读取',
    labelEdit: '编辑',
    labelWrite: '写入',
    labelSearch: '搜索',
    labelList: '列目录',
    labelSubagent: '子代理',
    /** 思考单元收起态标签（运行中同显 思考，运行态由脉冲点区分） */
    thought: '思考',
    /** 技能调用胶囊无障碍名（用户消息中 /skill:name 展开块的紧凑态） */
    skillChipLabel: (name: string): string => `技能 ${name}`,
    turnStoppedSummary: (elapsed: string): string => `已停止 · ${elapsed}`,
    /** 历史轮左缘锚点（无障碍名） */
    turnAnchorAria: (time: string): string => `查看 ${time} 结束的轮次`,
    /** 历史轮锚点带（无障碍名） */
    turnAnchorRailAria: '历史轮次导航',
    thinking: '思考',
    queued: (count: number): string => (count === 1 ? '1 条排队消息' : `${count} 条排队消息`),
    retrying: (attempt: number, maxAttempts: number): string => `重试中（${attempt}/${maxAttempts}）`,
    crashedBanner: '本会话的执行进程崩溃，正在恢复。下一条命令会自动续起。',
    compacting: '正在压缩上下文…',
    compactFailed: (reason: string): string => `压缩失败（${reason}）。`,
    bashRunning: '正在执行命令…',
    bashFailed: (reason: string): string => `命令未执行（${reason}）。`,
    queuePanelTitle: '排队消息',
    queueSteering: '即时改向（当前轮）',
    queueFollowUp: '本轮结束后发送',
    clearQueue: '清空全部排队',
    queueEmpty: '当前没有排队消息。',
    editRerun: '编辑并重开（分叉）',
    retryFromHere: '从这里重试',
    forkFailed: '分叉会话失败，请重试。',
    resumeFailed: '会话恢复失败，请重试。',
    sendModeSteer: '即时改向',
    sendModeQueue: '轮后发送',
    stopConfirmTitle: '停止全部任务？',
    stopConfirmHint: '将终止全部前台与后台子代理，且不可恢复。',
    stopConfirmYes: '全部停止',
    stopConfirmNo: '取消',
    bashNoImages: '直执行命令不支持携带图片，请移除附件或改用消息发送。',
    systemMessageLabel: '系统',
    sendFailed: (reason: string): string => `消息未发送（${reason}），请重试。`,
    toolFailed: (exitCode: number): string => `退出码 ${exitCode}`,
    copyMessage: '复制消息',
    editMessage: '编辑消息',
    scrollToBottom: '回到底部',
    copyCommand: '复制命令',
    copyOutput: '复制输出',
    copied: '已复制',
    outputLabel: '输出',
    toggleOutput: '展开/收起命令输出',
    panelWorking: (count: number): string => (count === 1 ? '1 个进行中' : `${count} 个进行中`),
    panelSettled: (count: number): string => (count === 1 ? '1 个已完成' : `${count} 个已完成`),
    notifySummary: (workingCount: number, tokens: number): string =>
      `${workingCount === 1 ? '1 个进行中' : `${workingCount} 个进行中`} Σ ${tokens}`,
    footerTokens: (tokens: string): string => `Σ ${tokens} tok`,
    metaTokens: (tokens: string | null): string => (tokens === null ? '— tok' : `${tokens} tok`),
    metaTools: (count: number): string | null => {
      if (count <= 0) return null;
      return count === 1 ? '1 个工具' : `${count} 个工具`;
    },
  },
  composer: {
    placeholder: '随便问；@ 引用文件，$ 使用技能，/ 选择命令',
    attach: '添加图片与文件',
    send: '发送消息',
    stop: '停止生成',
    contextUsage: '上下文占用',
    steerPlaceholder: '向该子代理注入指令…',
    steerFailed: (reason: string): string => `改向失败（${reason}）。`,
    compact: '立即压缩',
    noModels: '还没有模型——去设置添加',
    hostDownModels: '宿主未连接——模型暂不可选',
    effortUnavailable: '思考不可用',
    slashAria: '命令建议',
    fileAria: '文件建议',
    permissionMode: '权限模式',
    imageUnsupported: '只能附加不超过 20 MB 的常见格式图片（发送前会自动压缩）。',
    removeImage: '移除图片',
    localCheckout: '本地检出',
    checkoutMenu: ['main', 'v0.6.1', 'v0.6.2'],
    effortMenu: ['低 · 200K', '中 · 200K', '高 · 1M'],
  },
  dialogs: {
    confirmTitle: '需要确认',
    selectTitle: '请选择',
    inputTitle: '需要输入',
    allow: '允许',
    deny: '拒绝',
    cancel: '取消',
    send: '提交',
    noOptions: '没有可选项',
    morePending: (count: number): string => (count === 1 ? '还有 1 个请求等待' : `还有 ${count} 个请求等待`),
    fromSubagent: (agent: string): string => `子代理请求 · ${agent}`,
  },
  settings: {
    title: '设置',
    navGroupBasics: '基础设置',
    navGroupAgent: 'Agent 能力',
    navGroupData: '数据与统计',
    backToWorkspace: '返回工作区',
    navOnboarding: '引导',
    followSystem: '跟随系统',
    providersTitle: '模型设置',
    providersDesc: '模型来源与默认模型。',
    searchModels: '搜索模型…',
    searchNoResults: '没有匹配结果。',
    providersEmpty: '还没有配置 Provider，添加一个即可开始。',
    addProvider: '添加 Provider（OpenAI 兼容）',
    fieldName: '名称（如 glm）',
    fieldBaseUrl: 'Base URL（如 https://open.bigmodel.cn/api/paas/v4）',
    fieldModels: '模型 id（逗号分隔）',
    fieldKey: 'API key（留空保持不变）',
    modelThinkingOn: '已声明支持思考（点击关闭）',
    modelThinkingOff: '声明支持思考（点击开启）',
    modelVisionOn: '已声明支持视觉（点击关闭）',
    modelVisionOff: '声明支持视觉（点击开启；多模态模型必须打开，否则发送时图片被忽略）',
    modelThinkingMark: '思考',
    modelVisionMark: '视觉',
    thinkingFormatLabel: '思考参数形态',
    thinkingFormatHint: '按服务端接受的思考参数选择；模型勾选思考后，会话思考档位才可选。',
    thinkingFormatOptions: {
      default: '默认 · reasoning_effort',
      zai: '智谱 GLM · thinking 开关',
      qwen: 'Qwen · enable_thinking',
      deepseek: 'DeepSeek · thinking 开关',
      openrouter: 'OpenRouter · reasoning',
      together: 'Together · reasoning',
      'string-thinking': 'thinking 字符串',
      'ant-ling': '蚂蚁 Ling · reasoning',
    },
    keyPresent: '已保存 key',
    keyMissing: '缺少 key',
    save: '保存',
    remove: '移除',
    confirmRemove: '确认移除',
    formIncomplete: '名称、Base URL 和至少一个模型 id 必填。',
    formFailed: '保存失败，请检查后重试。',
    historyTitle: '历史',
    historyDesc: '恢复或管理已保存会话。',
    historyEmpty: '还没有已保存的会话。',
    historyFilterAll: '全部项目',
    historyFilter: (project: string): string => project,
    pin: '置顶',
    unpin: '取消置顶',
    revealInFinder: '在文件管理器中显示',
    historyMsgs: '条消息',
    refresh: '刷新',
    keysTitle: 'API 密钥',
    keysDesc: '官方 Provider 的 API key，只保存在宿主侧。',
    keysEmpty: '还没有配置官方 Provider 的 API key。',
    keysHint: 'key 只保存在 agent 宿主侧（auth.json），任何时候不会回显。Provider 名必须是宿主内置目录中的名称。',
    keysProviderField: 'Provider 名称（如 anthropic）',
    keysKeyField: 'API key',
    keysSave: '保存 key',
    keysRemove: '移除',
    keysConfirmRemove: '确认移除',
    keysFormIncomplete: 'Provider 名称与 API key 均必填。',
    keySaveFailed: (reason: string): string => `保存 key 失败（${reason}）。`,
    keyRemoveFailed: (reason: string): string => `移除 key 失败（${reason}）。`,
    preferenceSaveFailed: '偏好保存失败，请重试。',
    permissionSaveFailed: '权限规则保存失败，请重试。',
    permissionsTitle: '权限',
    permissionsDesc: '工具执行授权规则。',
    permissionsMode: '模式',
    permissionsModeAsk: '每次询问',
    permissionsModeAllowAll: '全部允许',
    permissionsModeBlockAll: '全部拒绝',
    permissionsModeHint: '判定顺序：先看模式，再匹配拒绝规则，再匹配允许规则，其余询问。',
    permissionsGlobHint: '通配符：* 匹配任意字符（含 /），其余按字面匹配。',
    permissionsBash: 'Bash 命令',
    permissionsWrite: '文件写入',
    permissionsEdit: '文件编辑',
    permissionsAllow: '始终允许',
    permissionsBlock: '始终拒绝',
    permissionsAddPattern: '添加规则…',
    permissionsSave: '保存规则',
    permissionsSaveFailed: '保存失败，请重试。',
    permissionsSaved: '规则已保存。',
    permissionsLoading: '正在加载权限规则…',
    permissionsScopeGlobal: '全部会话',
    permissionsScopeSession: '当前会话',
    permissionsFollowGlobal: '当前会话跟随全局规则。',
    permissionsCreateSession: '创建独立规则',
    permissionsFollowGlobalAction: '跟随全局规则',
    agentsTitle: '智能体',
    agentsDesc: '会话可用的智能体定义。',
    agentsEmpty: '没有找到 agent 定义。',
    agentsUserBadge: '用户级',
    agentsProjectBadge: '项目级 · 仅受信可见',
    agentsTools: (count: number): string => (count === 1 ? '1 个工具' : `${count} 个工具`),
    skillsTitle: '技能',
    skillsDesc: '用户级技能的启用与关闭。',
    searchSkills: '搜索技能…',
    skillsEmpty: '未安装用户级技能。',
    skillsHint: '用户级技能来自 agent 技能目录；关闭的技能在会话中不可用（保存后自动重开活跃会话生效，进行中的生成会被中断）。项目级技能只在受信会话中出现。',
    skillsRefresh: '刷新',
    skillDisabledHint: '已关闭：会话中不可用',
    skillToggleLabel: (name: string): string => `${name} 技能开关`,
    skillToggleFailed: '技能开关保存失败，请重试。',
    skillReopenFailed: '有会话重开失败，技能开关对它尚未生效。',
    diagnosticsTitle: '诊断',
    diagnosticsDesc: '宿主状态与排查。',
    diagnosticsPhase: '宿主相位',
    diagnosticsRegistry: '注册表会话数',
    diagnosticsStderr: '宿主 stderr（尾部）',
    diagnosticsRestart: '重启宿主',
    diagnosticsEmpty: '诊断信息尚未加载。',
    generalTitle: '常规',
    generalDesc: '语言、外观与基础行为。',
    generalLanguage: '界面语言',
    generalLanguageHint: '界面与系统文案的显示语言。',
    appearanceLabel: '外观',
    appearanceLight: '浅色',
    appearanceDark: '深色',
    appearanceHint: '界面配色，即时生效。',
    generalTrustedDefault: '默认信任新项目',
    generalTrustedHint: '受信会话会加载工作目录中的项目扩展与项目级 agent。',
    onboardingCardTitle: '引导',
    onboardingCardDesc: '重新运行新手引导：配置 Provider、选择默认模型并创建首个会话。',
    onboardingCardAction: '重新运行',
    generalSaveFailed: '保存失败，请重试。',
    generalDefaultModelInvalid: '默认模型已不可用；新会话将回落到首个可用模型。',
    defaultModelInvalidShort: '不可用',
    defaultModelTitle: '默认模型',
    defaultModelNone: '未设置（首个可用模型）',
    editProvider: '编辑',
    cancelEdit: '取消',
    nameLocked: 'Provider 创建后不可改名（改名会另立新条目）',
    testConnection: '测试连接',
    testing: '测试中…',
    testOk: (latencyMs: number): string => `正常 · ${latencyMs} ms`,
    testFailed: (reason: string): string => `失败（${reason}）`,
  },
  newThread: {
    title: '新会话',
    hint: '选择本会话的工作目录。agent 会读取并编辑该目录下的文件。',
    fieldCwd: '/path/to/project',
    trustedLabel: '信任此项目',
    trustedHint: '受信会话会加载项目扩展与项目级 agent。只对你拥有并审阅过的仓库开启。',
    create: '开始会话',
    browse: '浏览…（系统文件夹选择）',
    knownDirs: '已知项目目录',
    pickFailed: '目录选择器打开失败，请重试。',
    createFailed: (reason: string): string => {
      if (reason === 'host_unavailable') return 'agent 宿主未就绪（正在启动或重启），请稍后重试。';
      if (reason.startsWith('Model not found')) return '所选模型不可用，请在设置中检查 Provider 配置。';
      if (/cwd|directory|absolute|exist/i.test(reason)) return '无法开始会话，请检查目录后重试。';
      return `无法开始会话（${reason}），请重试。`;
    },
  },
  notices: {
    dismiss: '关闭',
  },
  usage: {
    title: '用量',
    close: '关闭',
    contextLabel: '上下文',
    tokensLabel: 'tokens',
    costLabel: '费用',
    messagesLabel: '消息',
    toolCallsLabel: '工具调用',
    totalTokens: '总 tokens',
    totalCost: '总费用',
    sessionsCount: (count: number): string => (count === 1 ? '1 个会话' : `${count} 个会话`),
    byProject: '按项目',
    topSessions: '会话排行',
    empty: '暂无带用量数据的活跃会话。',
    liveOnlyHint: '仅统计本次运行中的活跃会话；跨重启的用量历史暂未记录。',
  },
  onboarding: {
    title: '欢迎使用 pai',
    hint: '连接一个 Provider 并选择模型即可开始。也可以跳过，稍后在设置中配置。',
    stepProvider: '连接 Provider',
    stepModel: '选择默认模型',
    stepCwd: '选择工作目录',
    cwdField: '/path/to/your/project',
    next: '下一步',
    back: '上一步',
    finish: '开始对话',
    skip: '跳过配置',
    noModelsYet: '还没有模型。完成 Provider 配置或刷新。',
    refreshModels: '刷新',
  },
  bootstrap: {
    loadingTitle: '正在启动…',
    loadingHint: '正在连接 coding agent 宿主。',
    failedTitle: '无法启动',
    bridgeHint: '预加载桥不可用。请从桌面入口重新启动应用。',
    hostFailed: 'agent 宿主启动失败。请在设置中检查 Provider 配置与 pai-cli 路径。',
  },
  host: {
    downBanner: 'agent 宿主未连接，模型与会话暂不可用（已配置的 Provider 不受影响）。',
    downAction: '打开设置',
  },
  markdown: {
    copyCode: '复制代码',
    downloadDiagram: '下载图示',
    downloadDiagramSvg: '下载图示为 SVG',
    downloadDiagramPng: '下载图示为 PNG',
    downloadDiagramMmd: '下载图示为 MMD',
    viewFullscreen: '全屏查看',
    exitFullscreen: '退出全屏',
    mermaidFormatSvg: 'SVG',
    mermaidFormatPng: 'PNG',
    mermaidFormatMmd: 'MMD',
    zoomIn: '放大',
    zoomOut: '缩小',
    resetView: '重置缩放与平移',
    copyTable: '复制表格',
    copyTableAsMarkdown: '复制表格为 Markdown',
    copyTableAsCsv: '复制表格为 CSV',
    copyTableAsTsv: '复制表格为 TSV',
    downloadTable: '下载表格',
    downloadTableCsv: '下载表格为 CSV',
    downloadTableMarkdown: '下载表格为 Markdown',
    tableFormatMarkdown: 'Markdown',
    tableFormatCsv: 'CSV',
    tableFormatTsv: 'TSV',
    imageNotAvailable: '图片不可用',
    downloadImage: '下载图片',
    openExternalLink: '打开外部链接？',
    externalLinkWarning: '即将访问外部网站。',
    close: '关闭',
    copyLink: '复制链接',
    copied: '已复制',
    openLink: '打开链接',
  },
};
