import type { RetryCopy, ToolCopy } from '@paiapp/ui-thread';
import { retryLineOf } from '@paiapp/ui-thread';

/** 重试行词面（共享拼装入 @paiapp/ui-thread，两端同一句）：hub 错误码 → 原因短语。 */
export const retryCopy: RetryCopy = {
  reasonHttp429: '请求过于频繁',
  reasonHttp408: '请求超时',
  reasonHttp5xx: '上游服务暂时不可用',
  reasonNetwork: '网络中断',
  reasonRepetition: '检测到重复输出，正在换一段重试',
  reasonFallback: '暂时不可用',
  retryingLabel: (attempt: number): string => `重试中（第 ${attempt} 次）`,
};

export const copy = {
  appName: 'Pai Code',
  tagline: '把想法交给代码，把工作留在掌控中。',
  emptyTitle: '今天想完成什么？',
  emptyWorkspace: '选择工作空间',
  home: '对话',
  history: '对话历史',
  newChat: '新建对话',
  search: '搜索',
  settings: '设置',
  close: '关闭',
  cancel: '取消',
  confirm: '确认',
  done: '完成',
  send: '发送',
  stop: '停止生成',
  placeholder: '描述任务，或粘贴代码和错误信息…',
  selectWorkspace: '选择工作空间',
  workspaceHint: '选择 Pai Code 可以访问的代码目录',
  connectedComputer: '连接电脑',
  assets: '文件与附件',
  more: '更多',
  today: '今天',
  yesterday: '昨天',
  previous: '更早',
  pinned: '置顶',
  projects: '项目',
  recent: '最近对话',
  archive: '归档',
  delete: '删除',
  rename: '重命名',
  use: '使用',
  cancelChat: '结束对话',
  addAttachment: '添加附件',
  takePhoto: '拍照或从相册选择',
  chooseFile: '浏览文件',
  model: '模型',
  thinking: '思考强度',
  permission: '权限模式',
  askBefore: '每次询问',
  autoApprove: '自动批准',
  planOnly: '仅规划',
  tokenUsage: '上下文',
  noProject: '无项目',
  workspaceNoMatch: '没有匹配的工作区——可直接输入桌面端会话使用的目录路径。',
  workspaceHintText: '选择 Pai Code 可以访问的代码目录',
  taskConfigHint: '配置应用于当前对话；默认配置可在个人设置中调整。',
  taskConfigPending: '当前对话尚未在桌面端启动——先发送一条消息，配置即会同步过去。',
  settingsTitle: '个人设置',
  profile: '个人资料',
  appearance: '外观',
  preferences: '偏好设置',
  notifications: '通知与提醒',
  storage: '存储空间',
  privacy: '隐私与安全',
  help: '帮助与反馈',
  about: '关于 Pai Code',
  language: '界面语言',
  defaultModel: '默认模型',
  defaultThinking: '默认思考强度',
  defaultPermission: '默认权限模式',
  haptics: '触感反馈',
  system: '跟随系统',
  light: '浅色',
  dark: '深色',
  permissionExplain: '控制 Pai Code 执行命令和修改文件时需要你的确认。',
  quickAnalyze: '分析当前项目',
  quickFix: '定位并修复问题',
  quickReview: '审查代码质量',
  processLabel: '执行过程',
  turnLoadingLabel: 'Pai Code 正在生成回复',
  activityFailed: '执行遇到问题',
  activityRunning: '正在执行',
  running: '进行中',
  paused: '需要处理',
  detached: '需在电脑端打开',
  detachedEmptyChat: '这条对话已归档在电脑端，打开它后才能在这里继续。',
  demoConversation: '查看示例对话',
  unread: '未读',
  codeDefaultTitle: '代码',
  codeDefaultLanguage: 'text',
  codeLineUnit: '行',
  codeCollapse: '收起代码',
  expandCodeLines: (count: number) => `展开剩余 ${count} 行`,
  expandProcess: '展开过程流',
  collapseProcess: '收起过程流',
  expandToolGroup: '展开工具组',
  collapseToolGroup: '收起工具组',
  toolRowDetailLabel: (label: string) => `查看工具详情：${label}`,
  toolFailed: (exitCode: number) => `退出码 ${exitCode}`,
  toolDetailTitle: '工具执行详情',
  toolDetailCommand: '命令',
  toolDetailOutput: '输出',
  toolDetailNote: '完整命令与输出仅供查证，不在消息列表展示。',
  toolDetailFallback: '执行操作',
  fileDiffTitle: '改动详情',
  fileDiffUnknown: '未知文件',
  fileDiffDetailLabel: (name: string) => `查看改动详情：${name}`,
  thinkingLabel: '思考',
  expandThinking: '展开思考详情',
  collapseThinking: '收起思考详情',
  workingFor: (label: string) => `已工作 ${label}`,
  workedFor: (label: string) => `共工作 ${label}`,
  /** 重试行整句：拼装单点在 @paiapp/ui-thread/retry-copy（词面注入，两端同句）。 */
  retryLine: (attempt: number, code: string | null) => retryLineOf(attempt, code, retryCopy),
  notDelivered: '未送达',
  sendFailed: (reason: string) => `发送失败：${reason}`,
  sessionCreateFailed: '会话创建失败',
  hostUnavailable: '桌面端不可用',
  noReason: '桌面端未返回失败原因，请重试',
} as const;

/**
 * host/gateway 错误码 → 手机端原因短语。未知码走原样（可诊断性优先——
 * 吞成「未知错误」会让真机问题无从定位）。
 */
const REASON_COPY: Readonly<Record<string, string>> = {
  host_unavailable: copy.hostUnavailable,
  disconnected: '连接已断开',
  timeout: '响应超时',
  'scope-denied': '设备权限不足，请在桌面端调整设备作用域',
  'owner-only': '该操作仅桌面端可用',
  'unknown-command': '桌面端网关版本过旧，暂不支持该操作',
  'connect-exhausted': '无法连接桌面端，请确认其正在运行',
  no_active_session: '会话已失效',
  unknown_thread: '会话已在桌面端关闭',
  resume_failed: '会话恢复失败',
  model_unavailable: '模型不可用',
  no_session_path: '会话文件不可达',
  no_reason: copy.noReason,
};

export function copyReason(code: string | null | undefined): string {
  if (code === null || code === undefined || code.length === 0) return '未知错误';
  return REASON_COPY[code] ?? code;
}

/** 执行过程共享派生层（@paiapp/ui-thread）的中文文案注入面（词面与 PC 端同源）。 */
export const toolCopy: ToolCopy = {
  groupBashPhrase: '运行了命令',
  groupListPhrase: '列出了目录',
  groupEditPhrase: '编辑了文件',
  groupReadPhrase: '阅读了文件',
  groupSearchPhrase: '搜索了',
  groupSubagentPhrase: '派生了智能体',
  groupOtherPhrase: (name: string): string => `调用了${name}`,
  groupMorePhrase: '等',
  groupPhraseJoin: (phrases: readonly string[]): string => phrases.join(''),
  /** 整轮过程组的计数式标题（与 PC 端同源：词面一致才叫同一句话） */
  groupCountEdit: (count: number): string => `编辑 ${count} 个文件`,
  groupCountThinking: (count: number): string => `思考 ${count} 次`,
  groupCountRead: (count: number): string => `查看 ${count} 个文件`,
  groupCountSearch: (count: number): string => `搜索 ${count} 次`,
  groupCountList: (count: number): string => `列出 ${count} 个目录`,
  groupCountBash: (count: number): string => `运行 ${count} 条命令`,
  groupCountSubagent: (count: number): string => `派生 ${count} 个智能体`,
  groupCountOther: (count: number, name: string): string => (name.length > 0 ? `调用 ${count} 次 ${name}` : `调用 ${count} 次`),
  groupCountJoin: (phrases: readonly string[]): string => phrases.join(', '),
  rowDoneBash: '已运行',
  rowDoneRead: '已阅读',
  rowDoneEdit: '已编辑',
  rowDoneWrite: '已写入',
  rowDoneSearch: '已搜索',
  rowDoneList: '已列出',
  rowDoneSubagent: '已派生智能体',
  rowDoneOther: (name: string): string => `已调用${name}`,
  rowFailed: '运行失败',
  rowStopped: '已停止',
  rowFailedOther: (name: string): string => `调用失败${name}`,
  rowStoppedOther: (name: string): string => `已停止${name}`,
  rowRunningBash: '正在运行',
  rowRunningRead: '正在阅读',
  rowRunningEdit: '正在编辑',
  rowRunningWrite: '正在写入',
  rowRunningSearch: '正在搜索',
  rowRunningList: '正在列出',
  rowRunningSubagent: '正在派生智能体',
  rowRunningOther: (name: string): string => `正在调用${name}`,
};

export const models = [
  { id: 'gpt-5.2-codex', name: 'GPT-5.2 Codex', provider: 'OpenAI', description: '复杂工程与长上下文任务' },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', provider: 'Anthropic', description: '平衡推理速度与代码质量' },
  { id: 'gemini-3-pro', name: 'Gemini 3 Pro', provider: 'Google', description: '多模态理解与快速探索' },
  { id: 'qwen3-coder', name: 'Qwen3 Coder', provider: 'Alibaba', description: '本地与高性价比代码任务' },
] as const;

export const thinkingLevels = [
  { id: 'off', label: '关闭', detail: '最快响应，适合简单明确的任务' },
  { id: 'low', label: '低', detail: '轻量检查关键步骤' },
  { id: 'medium', label: '中', detail: '在质量与速度之间取得平衡' },
  { id: 'high', label: '高', detail: '更深入地分析复杂任务' },
] as const;

// host permission 值域（PROFILE_IDS：plan/auto/edit-confirm/full/sandboxed-auto——R2 M-1 对齐）
export const permissionModes = [
  { id: 'edit-confirm', label: '每次确认', detail: '执行命令或修改文件前请求确认' },
  { id: 'auto', label: '自动批准', detail: '在当前工作空间内自动批准常规操作' },
  { id: 'plan', label: '仅规划', detail: '只读取和规划，不执行有副作用的操作' },
  { id: 'full', label: '完全信任', detail: '全部操作免确认（含任意目录）' },
] as const;
