export const copy = {
  appName: 'Pai Code',
  tagline: '把想法交给代码，把工作留在掌控中。',
  home: '对话',
  history: '对话历史',
  newChat: '新建对话',
  search: '搜索',
  settings: '设置',
  close: '关闭',
  cancel: '取消',
  confirm: '确认',
  done: '完成',
  send: '发送',
  stop: '停止生成',
  placeholder: '描述任务，或粘贴代码和错误信息…',
  selectWorkspace: '选择工作空间',
  workspaceHint: '选择 Pai Code 可以访问的代码目录',
  connectedComputer: '连接电脑',
  assets: '文件与附件',
  more: '更多',
  today: '今天',
  yesterday: '昨天',
  previous: '更早',
  pinned: '置顶',
  projects: '项目',
  recent: '最近对话',
  archive: '归档',
  delete: '删除',
  rename: '重命名',
  use: '使用',
  cancelChat: '结束对话',
  addAttachment: '添加附件',
  takePhoto: '拍照或从相册选择',
  chooseFile: '浏览文件',
  model: '模型',
  thinking: '思考强度',
  permission: '权限模式',
  askBefore: '每次询问',
  autoApprove: '自动批准',
  planOnly: '仅规划',
  tokenUsage: '上下文',
  noProject: '无项目',
  settingsTitle: '个人设置',
  profile: '个人资料',
  appearance: '外观',
  preferences: '偏好设置',
  notifications: '通知与提醒',
  storage: '存储空间',
  privacy: '隐私与安全',
  help: '帮助与反馈',
  about: '关于 Pai Code',
  language: '界面语言',
  defaultModel: '默认模型',
  defaultThinking: '默认思考强度',
  defaultPermission: '默认权限模式',
  haptics: '触感反馈',
  system: '跟随系统',
  light: '浅色',
  dark: '深色',
  permissionExplain: '控制 Pai Code 执行命令和修改文件时需要你的确认。',
  quickAnalyze: '分析当前项目',
  quickFix: '定位并修复问题',
  quickReview: '审查代码质量',
} as const;

export const models = [
  { id: 'gpt-5.2-codex', name: 'GPT-5.2 Codex', provider: 'OpenAI', description: '复杂工程与长上下文任务' },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', provider: 'Anthropic', description: '平衡推理速度与代码质量' },
  { id: 'gemini-3-pro', name: 'Gemini 3 Pro', provider: 'Google', description: '多模态理解与快速探索' },
  { id: 'qwen3-coder', name: 'Qwen3 Coder', provider: 'Alibaba', description: '本地与高性价比代码任务' },
] as const;

export const thinkingLevels = [
  { id: 'off', label: '关闭', detail: '最快响应，适合简单明确的任务' },
  { id: 'low', label: '低', detail: '轻量检查关键步骤' },
  { id: 'medium', label: '中', detail: '在质量与速度之间取得平衡' },
  { id: 'high', label: '高', detail: '更深入地分析复杂任务' },
] as const;

export const permissionModes = [
  { id: 'ask', label: '每次询问', detail: '执行命令或修改文件前请求确认' },
  { id: 'auto', label: '自动批准', detail: '在当前工作空间内自动批准常规操作' },
  { id: 'plan', label: '仅规划', detail: '只读取和规划，不执行有副作用的操作' },
] as const;
